#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd); . "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);test_root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;reason_code=KISA_U26_ANALYSIS_PENDING;judgment_basis='/dev object types have not been evaluated';scan_completed=false;regular_file_count=0;block_device_count=0;char_device_count=0;excluded_runtime_count=0;unresolved_count=0;scan_error_count=0;collection_error='';record_limit=200000
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)collection_error=UNSUPPORTED_OS_CONFIGURATION;scan_error_count=1;;esac
find_bin=$(command -v find 2>/dev/null||true);timeout_bin=$(command -v timeout 2>/dev/null||true)
if [ -z "$collection_error" ]&&{ [ -z "$find_bin" ]||[ ! -x "$find_bin" ];};then collection_error=FIND_COMMAND_UNUSABLE;scan_error_count=1;fi
if [ -z "$collection_error" ]&&{ [ -z "$timeout_bin" ]||[ ! -x "$timeout_bin" ];};then collection_error=TIMEOUT_COMMAND_UNUSABLE;scan_error_count=1;fi
fixture_scan(){ IFS='|' read -r state regular block char excluded unresolved extra < "$1"||true;case "${state:-}" in complete|scan_error|timeout);;*)collection_error=SCAN_RESULT_PARSE_FAILED;scan_error_count=1;return 0;;esac;for v in "$regular" "$block" "$char" "$excluded" "$unresolved";do case "$v" in ''|*[!0-9]*)collection_error=SCAN_RESULT_PARSE_FAILED;scan_error_count=1;return 0;;esac;done;regular_file_count=$regular;block_device_count=$block;char_device_count=$char;excluded_runtime_count=$excluded;unresolved_count=$unresolved;if [ "$state" = complete ];then scan_completed=true;elif [ "$state" = timeout ];then collection_error=DEV_SCAN_TIMEOUT;scan_error_count=1;else collection_error=DEV_SCAN_FAILED;scan_error_count=1;fi;return 0;}
scan_dev(){ dev_root="${test_root}/dev";[ -d "$dev_root" ]||{ collection_error=DEV_NOT_FOUND;scan_error_count=1;return;};[ -e "$dev_root/mqueue" ]&&excluded_runtime_count=$((excluded_runtime_count+1));[ -e "$dev_root/shm" ]&&excluded_runtime_count=$((excluded_runtime_count+1));output=$($timeout_bin 10 "$find_bin" "$dev_root" -xdev \( -path "$dev_root/mqueue" -o -path "$dev_root/shm" \) -prune -o -printf '%y\n' 2>/dev/null);rc=$?;[ "$rc" -eq 124 ]&&{ collection_error=DEV_SCAN_TIMEOUT;scan_error_count=1;return;};[ "$rc" -eq 0 ]||{ collection_error=DEV_SCAN_FAILED;scan_error_count=1;return;};count=0;while IFS= read -r kind;do [ -n "$kind" ]||continue;count=$((count+1));[ "$count" -le "$record_limit" ]||{ collection_error=SCAN_RESULT_LIMIT_EXCEEDED;scan_error_count=1;return;};case "$kind" in f)regular_file_count=$((regular_file_count+1));;b)block_device_count=$((block_device_count+1));;c)char_device_count=$((char_device_count+1));;d|l|p|s);;*)unresolved_count=$((unresolved_count+1));;esac;done <<EOF
$output
EOF
scan_completed=true;}
if [ -z "$collection_error" ];then if [ -n "$test_root" ]&&[ -n "${OS_GUARD_TEST_SCAN_FILE:-}" ];then [ -r "$OS_GUARD_TEST_SCAN_FILE" ]&&fixture_scan "$OS_GUARD_TEST_SCAN_FILE"||collection_error=FIXTURE_SCAN_UNREADABLE;else scan_dev;fi;fi
if [ "$regular_file_count" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason_code=KISA_U26_REGULAR_FILE_FOUND;judgment_basis='One or more regular files were found under /dev outside the explicit mqueue and shm runtime exclusions'
elif [ -n "$collection_error" ]||[ "$scan_completed" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason_code=KISA_U26_SCAN_FAILED;judgment_basis='The bounded /dev object-type scan could not be completed';code=${collection_error:-DEV_SCAN_INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"/dev object scan failed"}')
elif [ "$unresolved_count" -gt 0 ];then status_json=null;review_state=PENDING;reason_code=KISA_U26_REVIEW_REQUIRED;judgment_basis='The completed /dev scan found object types requiring manual interpretation'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason_code=KISA_U26_NO_REGULAR_FILE_FOUND;judgment_basis='The completed bounded /dev scan found no regular file outside the explicit runtime exclusions';fi
printf '{"item_id":"U-26","status":%s,"review_state":"%s","current_value":{"scan_scope":"/dev","scan_completed":%s,"regular_file_count":%s,"block_device_count":%s,"char_device_count":%s,"excluded_runtime_count":%s,"unresolved_count":%s,"scan_error_count":%s},' "$status_json" "$review_state" "$scan_completed" "$regular_file_count" "$block_device_count" "$char_device_count" "$excluded_runtime_count" "$unresolved_count" "$scan_error_count"
printf '"evidence":{"item_id":"U-26","scan_scope":"/dev","collection_method":"Read-only fixed find object-type scan excluding /dev/mqueue and /dev/shm with xdev and timeout","scan_completed":%s,"regular_file_count":%s,"block_device_count":%s,"char_device_count":%s,"excluded_runtime_count":%s,"unresolved_count":%s,"scan_error_count":%s,"reason_code":' "$scan_completed" "$regular_file_count" "$block_device_count" "$char_device_count" "$excluded_runtime_count" "$unresolved_count" "$scan_error_count";os_guard_json_quote "$reason_code";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$judgment_basis";printf '},"error":%s}\n' "$error_json"
