#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);test_root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;reason_code=KISA_U27_ANALYSIS_PENDING;judgment_basis='Remote-command service and trust files have not been evaluated';service_detection_completed=false;r_command_active=false;trust_file_count=0;checked_file_count=0;owner_violation_count=0;permission_violation_count=0;plus_pattern_count=0;unresolved_count=0;collection_error=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)collection_error=UNSUPPORTED_OS_CONFIGURATION;;esac
stat_bin=$(command -v stat 2>/dev/null||true);systemctl_bin=$(command -v systemctl 2>/dev/null||true)
[ -n "$stat_bin" ]&&[ -x "$stat_bin" ]||collection_error=${collection_error:-STAT_COMMAND_UNUSABLE}
check_plus(){ if awk 'BEGIN{bad=0} /^[[:space:]]*($|#)/{next} {if($1=="+" || $2=="+")bad++} END{print bad}' "$1" 2>/dev/null;then :;else return 1;fi;}
inspect_trust(){ f=$1;allowed_name=$2;allowed_uid=$3;trust_file_count=$((trust_file_count+1));[ -f "$f" ]||{ unresolved_count=$((unresolved_count+1));return;};m=$($stat_bin -c '%u|%U|%a' -- "$f" 2>/dev/null)||{ collection_error=STAT_FAILED;return;};old=$IFS;IFS='|';set -- $m;IFS=$old;[ "$#" -eq 3 ]||{ collection_error=METADATA_PARSE_FAILED;return;};uid=$1;owner=$2;mode=$3;case "$uid:$owner" in 0:root) :;;"$allowed_uid:$allowed_name") :;;*)owner_violation_count=$((owner_violation_count+1));;esac;case "$mode" in [0-7][0-7][0-7]|[0-7][0-7][0-7][0-7]);;*)collection_error=METADATA_PARSE_FAILED;return;;esac;[ $(((0$mode)&~0600)) -eq 0 ]||permission_violation_count=$((permission_violation_count+1));plus=$(check_plus "$f")||{ collection_error=CONTENT_PARSE_FAILED;return;};plus_pattern_count=$((plus_pattern_count+plus));checked_file_count=$((checked_file_count+1));}
fixture(){ IFS='|' read -r state active files checked ownerbad modebad plus unresolved extra < "$1"||true;case "${state:-}" in complete|unknown|scan_error);;*)collection_error=SCAN_RESULT_PARSE_FAILED;return 0;;esac;case "$active" in 0|1);;*)collection_error=SCAN_RESULT_PARSE_FAILED;return 0;;esac;for v in "$files" "$checked" "$ownerbad" "$modebad" "$plus" "$unresolved";do case "$v" in ''|*[!0-9]*)collection_error=SCAN_RESULT_PARSE_FAILED;return 0;;esac;done;[ "$active" -eq 1 ]&&r_command_active=true;trust_file_count=$files;checked_file_count=$checked;owner_violation_count=$ownerbad;permission_violation_count=$modebad;plus_pattern_count=$plus;unresolved_count=$unresolved;if [ "$state" = complete ];then service_detection_completed=true;elif [ "$state" = unknown ];then collection_error=SERVICE_STATE_UNKNOWN;else collection_error=TRUST_FILE_SCAN_FAILED;fi;return 0;}
detect_services(){
 if [ -n "$systemctl_bin" ]&&[ -x "$systemctl_bin" ]&&[ -d "${test_root}/run/systemd/system" ];then service_detection_completed=true;for unit in rsh.socket rlogin.socket rexec.socket rsh.service rlogin.service rexec.service;do "$systemctl_bin" is-active --quiet "$unit" >/dev/null 2>&1&&r_command_active=true;done;fi
 for svc in rsh rlogin rexec;do cfg="${test_root}/etc/xinetd.d/$svc";if [ -r "$cfg" ];then service_detection_completed=true;awk 'BEGIN{IGNORECASE=1;on=0}/^[[:space:]]*disable[[:space:]]*=[[:space:]]*no([[:space:]]|$)/{on=1}END{exit on?0:1}' "$cfg"&&r_command_active=true;fi;done
 inetd="${test_root}/etc/inetd.conf";if [ -r "$inetd" ];then service_detection_completed=true;awk '/^[[:space:]]*($|#)/{next}$1~/^(shell|login|exec|rsh|rlogin|rexec)$/{on=1}END{exit on?0:1}' "$inetd"&&r_command_active=true;fi
 [ "$service_detection_completed" = true ]||collection_error=SERVICE_STATE_UNKNOWN
}
scan_trust(){ hosts="${test_root}/etc/hosts.equiv";if [ -e "$hosts" ]||[ -L "$hosts" ];then inspect_trust "$hosts" root 0;fi;[ -z "$collection_error" ]||return;pw="${test_root}/etc/passwd";[ -r "$pw" ]||{ collection_error=PASSWD_UNREADABLE;return;};accounts=0;while IFS=: read -r name x uid gid gecos home shell extra;do [ -n "$name$x$uid$gid$gecos$home$shell" ]||continue;case "$uid" in ''|*[!0-9]*)collection_error=PASSWD_PARSE_FAILED;break;;esac;accounts=$((accounts+1));f="${test_root}${home}/.rhosts";if [ -e "$f" ]||[ -L "$f" ];then inspect_trust "$f" "$name" "$uid";fi;[ -z "$collection_error" ]||break;done < "$pw";[ "$accounts" -gt 0 ]||collection_error=PASSWD_EMPTY_OR_INVALID;}
if [ -z "$collection_error" ];then if [ -n "$test_root" ]&&[ -n "${OS_GUARD_TEST_SCAN_FILE:-}" ];then [ -r "$OS_GUARD_TEST_SCAN_FILE" ]&&fixture "$OS_GUARD_TEST_SCAN_FILE"||collection_error=FIXTURE_SCAN_UNREADABLE;else detect_services;[ -z "$collection_error" ]&&[ "$r_command_active" = true ]&&scan_trust;fi;fi
if [ "$r_command_active" = true ]&&{ [ "$owner_violation_count" -gt 0 ]||[ "$permission_violation_count" -gt 0 ]||[ "$plus_pattern_count" -gt 0 ];};then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason_code=KISA_U27_TRUST_FILE_VIOLATION;judgment_basis='An active remote-command service has a trust file with invalid ownership, permission, or a plus trust pattern'
elif [ -n "$collection_error" ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason_code=KISA_U27_COLLECTION_FAILED;judgment_basis='Remote-command service state or required trust-file evidence could not be determined';error_json=$(printf '{"code":';os_guard_json_quote "$collection_error";printf ',"message":"remote-command trust assessment failed"}')
elif [ "$r_command_active" = true ]&&[ "$unresolved_count" -gt 0 ];then status_json=null;review_state=PENDING;reason_code=KISA_U27_REVIEW_REQUIRED;judgment_basis='An active remote-command service has a nonstandard or unresolved trust-file object requiring review'
else status_json='"GOOD"';review_state=NOT_REQUIRED;if [ "$r_command_active" = false ];then reason_code=KISA_U27_R_COMMAND_UNUSED;judgment_basis='rlogin, rsh, and rexec services are not active';else reason_code=KISA_U27_TRUST_CONDITIONS_MET;judgment_basis='Active remote-command services have only checked trust files with allowed ownership, 0600-subset permission, and no plus trust pattern';fi;fi
printf '{"item_id":"U-27","status":%s,"review_state":"%s","current_value":{"service_detection_completed":%s,"r_command_active":%s,"trust_file_count":%s,"checked_file_count":%s,"owner_violation_count":%s,"permission_violation_count":%s,"plus_pattern_count":%s,"unresolved_count":%s},' "$status_json" "$review_state" "$service_detection_completed" "$r_command_active" "$trust_file_count" "$checked_file_count" "$owner_violation_count" "$permission_violation_count" "$plus_pattern_count" "$unresolved_count"
printf '"evidence":{"item_id":"U-27","collection_method":"Read-only systemd/inetd/xinetd state and bounded trust-file metadata plus-pattern inspection","service_detection_completed":%s,"r_command_active":%s,"trust_file_count":%s,"checked_file_count":%s,"owner_violation_count":%s,"permission_violation_count":%s,"plus_pattern_count":%s,"unresolved_count":%s,"reason_code":' "$service_detection_completed" "$r_command_active" "$trust_file_count" "$checked_file_count" "$owner_violation_count" "$permission_violation_count" "$plus_pattern_count" "$unresolved_count";os_guard_json_quote "$reason_code";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$judgment_basis";printf '},"error":%s}\n' "$error_json"
