#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")"&&pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);test_root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;reason_code=KISA_U28_ANALYSIS_PENDING;judgment_basis='Host access-control mechanisms have not been evaluated';inspection_completed=false;mechanism_count=0;active_mechanism_count=0;inbound_filtering=false;restrictive_default_policy=false;explicit_rule_count=0;policy_verified=false;inspection_error_count=0;collection_error=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)collection_error=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state mechanisms active inbound restrictive rules verified errors extra < "$1"||true;case "${state:-}" in complete|scan_error);;*)collection_error=SCAN_RESULT_PARSE_FAILED;return 0;;esac;for v in "$mechanisms" "$active" "$inbound" "$restrictive" "$rules" "$verified" "$errors";do case "$v" in ''|*[!0-9]*)collection_error=SCAN_RESULT_PARSE_FAILED;return 0;;esac;done;mechanism_count=$mechanisms;active_mechanism_count=$active;[ "$inbound" -gt 0 ]&&inbound_filtering=true;[ "$restrictive" -gt 0 ]&&restrictive_default_policy=true;explicit_rule_count=$rules;[ "$verified" -gt 0 ]&&policy_verified=true;inspection_error_count=$errors;if [ "$state" = complete ];then inspection_completed=true;else collection_error=ACCESS_CONTROL_INSPECTION_FAILED;fi;return 0;}
inspect_live(){ attempted=0;succeeded=0
 nft_bin=$(command -v nft 2>/dev/null||true);if [ -n "$nft_bin" ]&&[ -x "$nft_bin" ];then attempted=$((attempted+1));out=$("$nft_bin" list ruleset 2>/dev/null);rc=$?;if [ "$rc" -eq 0 ];then succeeded=$((succeeded+1));mechanism_count=$((mechanism_count+1));if [ -n "$out" ];then active_mechanism_count=$((active_mechanism_count+1));printf '%s\n' "$out"|awk '/hook input/{ok=1}END{exit ok?0:1}'&&inbound_filtering=true;printf '%s\n' "$out"|awk '/policy (drop|reject)/{ok=1}END{exit ok?0:1}'&&restrictive_default_policy=true;c=$(printf '%s\n' "$out"|awk '/ (accept|drop|reject)([ ;]|$)/{n++}END{print n+0}');explicit_rule_count=$((explicit_rule_count+c));fi;else inspection_error_count=$((inspection_error_count+1));fi;fi
 ipt_bin=$(command -v iptables 2>/dev/null||true);if [ -n "$ipt_bin" ]&&[ -x "$ipt_bin" ];then attempted=$((attempted+1));out=$("$ipt_bin" -S INPUT 2>/dev/null);rc=$?;if [ "$rc" -eq 0 ];then succeeded=$((succeeded+1));mechanism_count=$((mechanism_count+1));[ -n "$out" ]&&active_mechanism_count=$((active_mechanism_count+1));printf '%s\n' "$out"|awk '/^-A INPUT /{ok=1}END{exit ok?0:1}'&&inbound_filtering=true;printf '%s\n' "$out"|awk '/^-P INPUT (DROP|REJECT)$/{ok=1}END{exit ok?0:1}'&&restrictive_default_policy=true;c=$(printf '%s\n' "$out"|awk '/^-A INPUT /{n++}END{print n+0}');explicit_rule_count=$((explicit_rule_count+c));else inspection_error_count=$((inspection_error_count+1));fi;fi
 fw_bin=$(command -v firewall-cmd 2>/dev/null||true);if [ -n "$fw_bin" ]&&[ -x "$fw_bin" ];then attempted=$((attempted+1));if "$fw_bin" --state >/dev/null 2>&1;then succeeded=$((succeeded+1));mechanism_count=$((mechanism_count+1));active_mechanism_count=$((active_mechanism_count+1));out=$($fw_bin --list-all 2>/dev/null)||inspection_error_count=$((inspection_error_count+1));if [ -n "${out:-}" ];then c=$(printf '%s\n' "$out"|awk -F: '/^[[:space:]]*(services|ports|rich rules):/{if($2~/[^[:space:]]/)n++}END{print n+0}');explicit_rule_count=$((explicit_rule_count+c));[ "$c" -gt 0 ]&&inbound_filtering=true;fi;else succeeded=$((succeeded+1));fi;fi
 ufw_bin=$(command -v ufw 2>/dev/null||true);if [ -n "$ufw_bin" ]&&[ -x "$ufw_bin" ];then attempted=$((attempted+1));out=$("$ufw_bin" status verbose 2>/dev/null);rc=$?;if [ "$rc" -eq 0 ];then succeeded=$((succeeded+1));mechanism_count=$((mechanism_count+1));printf '%s\n' "$out"|awk '/^Status: active/{ok=1}END{exit ok?0:1}'&&active_mechanism_count=$((active_mechanism_count+1));printf '%s\n' "$out"|awk '/Default: (deny|reject) \(incoming\)/{ok=1}END{exit ok?0:1}'&&restrictive_default_policy=true;c=$(printf '%s\n' "$out"|awk '/[[:space:]](ALLOW|DENY|REJECT)[[:space:]]/{n++}END{print n+0}');explicit_rule_count=$((explicit_rule_count+c));[ "$c" -gt 0 ]&&inbound_filtering=true;else inspection_error_count=$((inspection_error_count+1));fi;fi
 if [ -r "${test_root}/etc/hosts.allow" ]||[ -r "${test_root}/etc/hosts.deny" ];then mechanism_count=$((mechanism_count+1));fi
 if [ "$attempted" -eq 0 ];then inspection_completed=true
 elif [ "$succeeded" -gt 0 ];then inspection_completed=true
 else collection_error=ACCESS_CONTROL_INSPECTION_FAILED;fi
}
if [ -z "$collection_error" ];then if [ -n "$test_root" ]&&[ -n "${OS_GUARD_TEST_SCAN_FILE:-}" ];then [ -r "$OS_GUARD_TEST_SCAN_FILE" ]&&fixture "$OS_GUARD_TEST_SCAN_FILE"||collection_error=FIXTURE_SCAN_UNREADABLE;else inspect_live;fi;fi
if [ -n "$collection_error" ]||[ "$inspection_completed" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason_code=KISA_U28_COLLECTION_FAILED;judgment_basis='Host access-control mechanisms could not be inspected reliably';code=${collection_error:-ACCESS_CONTROL_INSPECTION_INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"access-control inspection failed"}')
elif [ "$active_mechanism_count" -eq 0 ]||[ "$inbound_filtering" != true ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason_code=KISA_U28_NO_ACTIVE_INBOUND_RESTRICTION;judgment_basis='No active host access-control mechanism with inbound filtering was identified'
elif [ "$policy_verified" = true ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason_code=KISA_U28_VERIFIED_ACCESS_RESTRICTION;judgment_basis='Active inbound access restrictions are present and match an approved local access policy'
else status_json=null;review_state=PENDING;reason_code=KISA_U28_POLICY_REVIEW_REQUIRED;judgment_basis='Technical inbound filtering exists, but the allowed IP and port policy requires administrative validation';fi
printf '{"item_id":"U-28","status":%s,"review_state":"%s","current_value":{"inspection_completed":%s,"mechanism_count":%s,"active_mechanism_count":%s,"inbound_filtering":%s,"restrictive_default_policy":%s,"explicit_rule_count":%s,"policy_verified":%s,"inspection_error_count":%s},' "$status_json" "$review_state" "$inspection_completed" "$mechanism_count" "$active_mechanism_count" "$inbound_filtering" "$restrictive_default_policy" "$explicit_rule_count" "$policy_verified" "$inspection_error_count"
printf '"evidence":{"item_id":"U-28","collection_method":"Read-only aggregate inspection of available host access-control mechanisms without exporting rules or addresses","inspection_completed":%s,"mechanism_count":%s,"active_mechanism_count":%s,"inbound_filtering":%s,"restrictive_default_policy":%s,"explicit_rule_count":%s,"policy_verified":%s,"inspection_error_count":%s,"reason_code":' "$inspection_completed" "$mechanism_count" "$active_mechanism_count" "$inbound_filtering" "$restrictive_default_policy" "$explicit_rule_count" "$policy_verified" "$inspection_error_count";os_guard_json_quote "$reason_code";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$judgment_basis";printf '},"error":%s}\n' "$error_json"
