#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd); . "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown}; version_id=${OS_GUARD_VERSION_ID:-unknown}; module_version=${OS_GUARD_MODULE_VERSION:-unknown}; observed_at=$(os_guard_utc_now); kernel=$(uname -r 2>/dev/null || printf unknown); root=${OS_GUARD_TEST_ROOT:-}
status_json=null; review_state=PENDING; reason_code=KISA_U31_NOT_EVALUATED; basis='Home directory metadata was not evaluated'; error_json=null
account_count=0; home_checked_count=0; owner_violation_count=0; write_violation_count=0; acl_write_count=0; unresolved_count=0; collection_error=''; scan_completed=false
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*) ;; *) collection_error=UNSUPPORTED_OS_CONFIGURATION;; esac
if [ -z "$collection_error" ] && [ -n "${OS_GUARD_TEST_HOME_SCAN_FILE:-}" ]; then IFS='|' read -r state accounts checked owner_bad write_bad acl_bad unresolved extra < "$OS_GUARD_TEST_HOME_SCAN_FILE" || true; case "$state" in complete|scan_error) ;; *) collection_error=RESULT_PARSE_FAILED;; esac; for v in "$accounts" "$checked" "$owner_bad" "$write_bad" "$acl_bad" "$unresolved"; do case "$v" in ''|*[!0-9]*) collection_error=RESULT_PARSE_FAILED;; esac; done; account_count=${accounts:-0}; home_checked_count=${checked:-0}; owner_violation_count=${owner_bad:-0}; write_violation_count=${write_bad:-0}; acl_write_count=${acl_bad:-0}; unresolved_count=${unresolved:-0}; [ "$state" = complete ] && scan_completed=true || collection_error=HOME_SCAN_FAILED
elif [ -z "$collection_error" ]; then
 passwd_file="${root}/etc/passwd"; stat_bin=$(command -v stat 2>/dev/null || true); getfacl_bin=$(command -v getfacl 2>/dev/null || true)
 if [ ! -r "$passwd_file" ]; then collection_error=PASSWD_UNREADABLE; elif [ -z "$stat_bin" ]; then collection_error=STAT_COMMAND_UNUSABLE; else
  while IFS=: read -r n x uid gid c home shell extra; do [ -n "$n$x$uid$gid$c$home$shell" ] || continue; case "$uid:$gid" in *[!0-9:]*|:*) collection_error=PASSWD_PARSE_FAILED; break;; esac; account_count=$((account_count+1)); [ -n "$home" ] || { unresolved_count=$((unresolved_count+1)); continue; }; path="${root}${home}"; [ -d "$path" ] || { unresolved_count=$((unresolved_count+1)); continue; }; meta=$($stat_bin -c '%u|%g|%a' -- "$path" 2>/dev/null) || { collection_error=STAT_FAILED; break; }; old=$IFS; IFS='|'; set -- $meta; IFS=$old; [ "$#" -eq 3 ] || { collection_error=METADATA_PARSE_FAILED; break; }; case "$1:$2:$3" in *[!0-9:]* ) collection_error=METADATA_PARSE_FAILED; break;; esac; home_checked_count=$((home_checked_count+1)); [ "$1" -eq "$uid" ] || owner_violation_count=$((owner_violation_count+1)); m=$((0$3)); [ $((m & 0002)) -eq 0 ] || write_violation_count=$((write_violation_count+1)); if [ $((m & 0020)) -ne 0 ]; then members=$(getent group "$2" 2>/dev/null || true); case "$members" in *:*) printf '%s' "$members" | awk -F: -v u="$n" '$4==""||$4==u{exit 1}{exit 0}' && write_violation_count=$((write_violation_count+1)) || unresolved_count=$((unresolved_count+1));; *) unresolved_count=$((unresolved_count+1));; esac; fi; if [ -n "$getfacl_bin" ]; then $getfacl_bin -cp -- "$path" 2>/dev/null | awk -F: '/^user:[^:]+:/&&$3~/w/{x=1}/^other::/&&$3~/w/{x=1}END{exit x?0:1}' && acl_write_count=$((acl_write_count+1)); fi; done < "$passwd_file"; [ "$account_count" -gt 0 ] || collection_error=PASSWD_EMPTY_OR_INVALID; [ -z "$collection_error" ] && scan_completed=true
 fi
fi
if [ "$owner_violation_count" -gt 0 ] || [ "$write_violation_count" -gt 0 ] || [ "$acl_write_count" -gt 0 ]; then status_json='"VULNERABLE"'; review_state=NOT_REQUIRED; reason_code=KISA_U31_OWNER_OR_WRITE_VIOLATION; basis='A home directory has a mismatched owner or confirmed write access for another principal'
elif [ -n "$collection_error" ] || [ "$scan_completed" != true ]; then status_json='"UNCHECKABLE"'; review_state=NOT_REQUIRED; reason_code=KISA_U31_COLLECTION_FAILED; basis='Account-home metadata collection could not be completed'; code=${collection_error:-HOME_SCAN_INCOMPLETE}; error_json=$(printf '{"code":'; os_guard_json_quote "$code"; printf ',"message":"home directory metadata collection failed"}')
elif [ "$unresolved_count" -gt 0 ]; then status_json=null; review_state=PENDING; reason_code=KISA_U31_RELATIONSHIP_UNRESOLVED; basis='An NSS, ACL, group-membership, or account-home relationship requires review'
else status_json='"GOOD"'; review_state=NOT_REQUIRED; reason_code=KISA_U31_OWNER_AND_WRITE_COMPLIANT; basis='All checked home directories are owned by their account and have no confirmed write access for other principals'; fi
printf '{"item_id":"U-31","status":%s,"review_state":"%s","current_value":{"account_count":%s,"home_checked_count":%s,"owner_violation_count":%s,"write_violation_count":%s,"acl_write_count":%s,"unresolved_count":%s,"scan_completed":%s},' "$status_json" "$review_state" "$account_count" "$home_checked_count" "$owner_violation_count" "$write_violation_count" "$acl_write_count" "$unresolved_count" "$scan_completed"
printf '"evidence":{"item_id":"U-31","inspection_target":"passwd account home directory metadata","collection_method":"Read-only passwd relationship and stat/ACL metadata inspection","account_count":%s,"home_checked_count":%s,"owner_violation_count":%s,"write_violation_count":%s,"acl_write_count":%s,"unresolved_count":%s,"scan_completed":%s,"reason_code":' "$account_count" "$home_checked_count" "$owner_violation_count" "$write_violation_count" "$acl_write_count" "$unresolved_count" "$scan_completed"; os_guard_json_quote "$reason_code"; printf ',"os":{"distro":'; os_guard_json_quote "$distro"; printf ',"version_id":'; os_guard_json_quote "$version_id"; printf '},"kernel":'; os_guard_json_quote "$kernel"; printf ',"module_version":'; os_guard_json_quote "$module_version"; printf ',"observed_at":'; os_guard_json_quote "$observed_at"; printf ',"judgment_basis":'; os_guard_json_quote "$basis"; printf '},"error":%s}\n' "$error_json"
