#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd); . "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown}; version_id=${OS_GUARD_VERSION_ID:-unknown}; module_version=${OS_GUARD_MODULE_VERSION:-unknown}; observed_at=$(os_guard_utc_now); kernel=$(uname -r 2>/dev/null || printf unknown); root=${OS_GUARD_TEST_ROOT:-}
status_json=null; review_state=PENDING; reason_code=KISA_U32_NOT_EVALUATED; basis='Home directory existence was not evaluated'; error_json=null
account_count=0; home_checked_count=0; missing_home_count=0; unresolved_count=0; scan_completed=false; collection_error=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*) ;; *) collection_error=UNSUPPORTED_OS_CONFIGURATION;; esac
if [ -z "$collection_error" ] && [ -n "${OS_GUARD_TEST_HOME_EXISTENCE_FILE:-}" ]; then IFS='|' read -r state accounts checked missing unresolved extra < "$OS_GUARD_TEST_HOME_EXISTENCE_FILE" || true; case "$state" in complete|scan_error) ;; *) collection_error=RESULT_PARSE_FAILED;; esac; for v in "$accounts" "$checked" "$missing" "$unresolved"; do case "$v" in ''|*[!0-9]*) collection_error=RESULT_PARSE_FAILED;; esac; done; account_count=${accounts:-0}; home_checked_count=${checked:-0}; missing_home_count=${missing:-0}; unresolved_count=${unresolved:-0}; [ "$state" = complete ] && scan_completed=true || collection_error=HOME_EXISTENCE_SCAN_FAILED
elif [ -z "$collection_error" ]; then
 passwd_file="${root}/etc/passwd"
 if [ ! -r "$passwd_file" ]; then collection_error=PASSWD_UNREADABLE; else
  while IFS=: read -r n x uid gid c home shell extra; do [ -n "$n$x$uid$gid$c$home$shell" ] || continue; case "$uid:$gid" in *[!0-9:]*|:*) collection_error=PASSWD_PARSE_FAILED; break;; esac; account_count=$((account_count+1)); if [ -z "$home" ] || [ "${home#/}" = "$home" ]; then unresolved_count=$((unresolved_count+1)); continue; fi; home_checked_count=$((home_checked_count+1)); path="${root}${home}"; if [ -e "$path" ] || [ -L "$path" ]; then [ -d "$path" ] || unresolved_count=$((unresolved_count+1)); else missing_home_count=$((missing_home_count+1)); fi; done < "$passwd_file"; [ "$account_count" -gt 0 ] || collection_error=PASSWD_EMPTY_OR_INVALID; [ -z "$collection_error" ] && scan_completed=true
 fi
fi
if [ "$missing_home_count" -gt 0 ]; then status_json='"VULNERABLE"'; review_state=NOT_REQUIRED; reason_code=KISA_U32_MISSING_HOME_FOUND; basis='At least one passwd account designates a home directory that does not exist'
elif [ -n "$collection_error" ] || [ "$scan_completed" != true ]; then status_json='"UNCHECKABLE"'; review_state=NOT_REQUIRED; reason_code=KISA_U32_COLLECTION_FAILED; basis='Passwd or home existence collection could not be completed'; code=${collection_error:-HOME_SCAN_INCOMPLETE}; error_json=$(printf '{"code":'; os_guard_json_quote "$code"; printf ',"message":"home existence collection failed"}')
elif [ "$unresolved_count" -gt 0 ]; then status_json=null; review_state=PENDING; reason_code=KISA_U32_HOME_RELATIONSHIP_UNRESOLVED; basis='A nonstandard or dynamic account-home relationship requires review'
else status_json='"GOOD"'; review_state=NOT_REQUIRED; reason_code=KISA_U32_ALL_HOMES_EXIST; basis='Every checked passwd account designates an existing home directory'; fi
printf '{"item_id":"U-32","status":%s,"review_state":"%s","current_value":{"account_count":%s,"home_checked_count":%s,"missing_home_count":%s,"unresolved_count":%s,"scan_completed":%s},' "$status_json" "$review_state" "$account_count" "$home_checked_count" "$missing_home_count" "$unresolved_count" "$scan_completed"
printf '"evidence":{"item_id":"U-32","inspection_target":"passwd-designated home directory existence","collection_method":"Read-only passwd parsing and filesystem existence checks","account_count":%s,"home_checked_count":%s,"missing_home_count":%s,"unresolved_count":%s,"scan_completed":%s,"reason_code":' "$account_count" "$home_checked_count" "$missing_home_count" "$unresolved_count" "$scan_completed"; os_guard_json_quote "$reason_code"; printf ',"os":{"distro":'; os_guard_json_quote "$distro"; printf ',"version_id":'; os_guard_json_quote "$version_id"; printf '},"kernel":'; os_guard_json_quote "$kernel"; printf ',"module_version":'; os_guard_json_quote "$module_version"; printf ',"observed_at":'; os_guard_json_quote "$observed_at"; printf ',"judgment_basis":'; os_guard_json_quote "$basis"; printf '},"error":%s}\n' "$error_json"
