#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd); . "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown}; version_id=${OS_GUARD_VERSION_ID:-unknown}; module_version=${OS_GUARD_MODULE_VERSION:-unknown}; observed_at=$(os_guard_utc_now); kernel=$(uname -r 2>/dev/null || printf unknown); root=${OS_GUARD_TEST_ROOT:-}
status_json=null; review_state=PENDING; reason_code=KISA_U33_NOT_EVALUATED; basis='Hidden filesystem entries were not evaluated'; error_json=null
hidden_file_count=0; hidden_directory_count=0; approved_count=0; suspicious_count=0; unresolved_count=0; warning_count=0; scan_completed=false; timeout=false; truncated=false; collection_error=''; record_limit=100000
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*) ;; *) collection_error=UNSUPPORTED_OS_CONFIGURATION;; esac
process_fixture(){ IFS='|' read -r state files dirs approved suspicious unresolved warnings extra < "$1" || true; case "$state" in complete|scan_error|timeout|truncated) ;; *) collection_error=RESULT_PARSE_FAILED; return;; esac; for v in "$files" "$dirs" "$approved" "$suspicious" "$unresolved" "$warnings"; do case "$v" in ''|*[!0-9]*) collection_error=RESULT_PARSE_FAILED; return;; esac; done; hidden_file_count=$files; hidden_directory_count=$dirs; approved_count=$approved; suspicious_count=$suspicious; unresolved_count=$unresolved; warning_count=$warnings; case "$state" in complete) scan_completed=true;; timeout) timeout=true; collection_error=FILESYSTEM_SCAN_TIMEOUT;; truncated) truncated=true; collection_error=SCAN_RESULT_LIMIT_EXCEEDED;; *) collection_error=FILESYSTEM_SCAN_FAILED;; esac; }
scan_root(){ find_bin=$(command -v find 2>/dev/null || true); timeout_bin=$(command -v timeout 2>/dev/null || true); [ -n "$find_bin" ] && [ -n "$timeout_bin" ] || { collection_error=SCAN_COMMAND_UNUSABLE; return; }; output=$($timeout_bin 10 "$find_bin" / -xdev \( -type f -o -type d \) -name '.*' -printf '%y\n' 2>/dev/null); rc=$?; [ "$rc" -ne 124 ] || { timeout=true; collection_error=FILESYSTEM_SCAN_TIMEOUT; return; }; [ "$rc" -eq 0 ] || { collection_error=FILESYSTEM_SCAN_FAILED; return; }; count=0; while IFS= read -r kind; do [ -n "$kind" ] || continue; count=$((count+1)); if [ "$count" -gt "$record_limit" ]; then truncated=true; collection_error=SCAN_RESULT_LIMIT_EXCEEDED; return; fi; case "$kind" in f) hidden_file_count=$((hidden_file_count+1));; d) hidden_directory_count=$((hidden_directory_count+1));; *) collection_error=SCAN_RESULT_PARSE_FAILED; return;; esac; done <<EOF
$output
EOF
 scan_completed=true; }
if [ -z "$collection_error" ]; then if [ -n "${OS_GUARD_TEST_HIDDEN_SCAN_FILE:-}" ]; then [ -r "$OS_GUARD_TEST_HIDDEN_SCAN_FILE" ] && process_fixture "$OS_GUARD_TEST_HIDDEN_SCAN_FILE" || collection_error=FIXTURE_SCAN_UNREADABLE; else scan_root; fi; fi
total=$((hidden_file_count+hidden_directory_count))
if [ "$suspicious_count" -gt 0 ]; then status_json='"VULNERABLE"'; review_state=NOT_REQUIRED; reason_code=KISA_U33_VERIFIED_SUSPICIOUS_ENTRY; basis='A hidden entry was verified as unnecessary or suspicious by approved local policy'
elif [ -n "$collection_error" ] || [ "$scan_completed" != true ]; then status_json='"UNCHECKABLE"'; review_state=NOT_REQUIRED; reason_code=KISA_U33_SCAN_INCOMPLETE; basis='The bounded hidden-entry filesystem scan did not complete'; code=${collection_error:-FILESYSTEM_SCAN_INCOMPLETE}; error_json=$(printf '{"code":'; os_guard_json_quote "$code"; printf ',"message":"hidden entry scan failed"}')
elif [ "$total" -eq 0 ]; then status_json='"GOOD"'; review_state=NOT_REQUIRED; reason_code=KISA_U33_NONE_FOUND; basis='The completed bounded scan found no hidden file or directory'
elif [ "$approved_count" -eq "$total" ] && [ "$unresolved_count" -eq 0 ]; then status_json='"GOOD"'; review_state=NOT_REQUIRED; reason_code=KISA_U33_ALL_LOCALLY_APPROVED; basis='All hidden entries are covered by an approved local policy'
else status_json=null; review_state=PENDING; reason_code=KISA_U33_REVIEW_REQUIRED; basis='Hidden entries exist but their operational necessity or suspiciousness cannot be established automatically'; fi
printf '{"item_id":"U-33","status":%s,"review_state":"%s","current_value":{"hidden_file_count":%s,"hidden_directory_count":%s,"approved_count":%s,"suspicious_count":%s,"unresolved_count":%s,"warning_count":%s,"scan_completed":%s,"timeout":%s,"truncated":%s},' "$status_json" "$review_state" "$hidden_file_count" "$hidden_directory_count" "$approved_count" "$suspicious_count" "$unresolved_count" "$warning_count" "$scan_completed" "$timeout" "$truncated"
printf '"evidence":{"item_id":"U-33","inspection_target":"root filesystem hidden files and directories","collection_method":"Read-only GNU find scan with xdev, timeout, result-limit, and type-only output","hidden_file_count":%s,"hidden_directory_count":%s,"approved_count":%s,"suspicious_count":%s,"unresolved_count":%s,"warning_count":%s,"scan_completed":%s,"timeout":%s,"truncated":%s,"reason_code":' "$hidden_file_count" "$hidden_directory_count" "$approved_count" "$suspicious_count" "$unresolved_count" "$warning_count" "$scan_completed" "$timeout" "$truncated"; os_guard_json_quote "$reason_code"; printf ',"os":{"distro":'; os_guard_json_quote "$distro"; printf ',"version_id":'; os_guard_json_quote "$version_id"; printf '},"kernel":'; os_guard_json_quote "$kernel"; printf ',"module_version":'; os_guard_json_quote "$module_version"; printf ',"observed_at":'; os_guard_json_quote "$observed_at"; printf ',"judgment_basis":'; os_guard_json_quote "$basis"; printf '},"error":%s}\n' "$error_json"
