#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd); . "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown}; version_id=${OS_GUARD_VERSION_ID:-unknown}; module_version=${OS_GUARD_MODULE_VERSION:-unknown}; observed_at=$(os_guard_utc_now); kernel=$(uname -r 2>/dev/null||printf unknown); root=${OS_GUARD_TEST_ROOT:-}
status_json=null; review_state=PENDING; error_json=null; present=0; active=0; socket_active=0; inetd_enabled=0; xinetd_enabled=0; unresolved=0; complete=false; err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*) err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state present active socket_active inetd_enabled xinetd_enabled unresolved extra < "$1"||true; case "$state" in complete) complete=true;;*) err=SERVICE_STATE_COLLECTION_FAILED;;esac; for v in "$present" "$active" "$socket_active" "$inetd_enabled" "$xinetd_enabled" "$unresolved";do case "$v" in ''|*[!0-9]*) err=RESULT_PARSE_FAILED;;esac;done; }
runtime(){ systemctl_bin=$(command -v systemctl 2>/dev/null||true); if [ -n "$systemctl_bin" ];then for u in finger.service fingerd.service finger.socket fingerd.socket;do state=$($systemctl_bin is-active "$u" 2>/dev/null||true); [ "$state" = active ]&&{ case "$u" in *.socket) socket_active=$((socket_active+1));;*) active=$((active+1));;esac; }; $systemctl_bin list-unit-files "$u" --no-legend 2>/dev/null|grep -q .&&present=$((present+1));done;fi; for f in "${root}/etc/inetd.conf" "${root}/etc/xinetd.d/finger";do [ -r "$f" ]||continue; present=$((present+1)); case "$f" in *inetd.conf) grep -E '^[[:space:]]*finger[[:space:]]' "$f" >/dev/null&&inetd_enabled=$((inetd_enabled+1));;*) grep -Eiq 'disable[[:space:]]*=[[:space:]]*no' "$f"&&xinetd_enabled=$((xinetd_enabled+1));;esac;done; complete=true; }
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_SERVICE_FILE:-}" ];then fixture "$OS_GUARD_TEST_SERVICE_FILE";else runtime;fi;fi
if [ "$active" -gt 0 ]||[ "$socket_active" -gt 0 ]||[ "$inetd_enabled" -gt 0 ]||[ "$xinetd_enabled" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U34_FINGER_ACTIVE;basis='A Finger service activation path is active'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U34_COLLECTION_FAILED;basis='Finger service state could not be collected completely';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"Finger service state collection failed"}')
elif [ "$unresolved" -gt 0 ];then status_json=null;review_state=PENDING;reason=KISA_U34_STATE_CONFLICT;basis='Conflicting service state requires review'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U34_FINGER_INACTIVE;basis='No active Finger service path was identified';fi
printf '{"item_id":"U-34","status":%s,"review_state":"%s","current_value":{"service_present":%s,"service_active":%s,"socket_active":%s,"inetd_enabled":%s,"xinetd_enabled":%s,"unresolved_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-34","collection_method":"Read-only systemd, inetd and xinetd activation inspection","service_present":%s,"service_active":%s,"socket_active":%s,"inetd_enabled":%s,"xinetd_enabled":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$present" "$active" "$socket_active" "$inetd_enabled" "$xinetd_enabled" "$unresolved" "$complete" "$present" "$active" "$socket_active" "$inetd_enabled" "$xinetd_enabled" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
