#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd); . "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;active=0;anonymous=0;restricted=0;unresolved=0;complete=false;err=''; ftp_active=0;nfs_active=0;samba_active=0
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked active anonymous restricted unresolved ftp_active nfs_active samba_active extra < "$1"||true;case "$state" in complete)complete=true;;*)err=SHARE_SERVICE_COLLECTION_FAILED;;esac;for v in "$checked" "$active" "$anonymous" "$restricted" "$unresolved" "$ftp_active" "$nfs_active" "$samba_active";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
is_active(){ command -v systemctl >/dev/null 2>&1&&systemctl is-active "$1" 2>/dev/null|grep -qx active;}
runtime(){ for u in vsftpd.service proftpd.service pure-ftpd.service;do checked=$((checked+1));if is_active "$u";then active=$((active+1));ftp_active=$((ftp_active+1)); found=false;for f in "${root}/etc/vsftpd/vsftpd.conf" "${root}/etc/vsftpd.conf" "${root}/etc/proftpd/proftpd.conf";do [ -r "$f" ]||continue;found=true;if grep -Eiq '^(anonymous_enable[[:space:]]*=[[:space:]]*YES|Anonymous[[:space:]]+)' "$f";then anonymous=$((anonymous+1));else restricted=$((restricted+1));fi;done;[ "$found" = true ]||unresolved=$((unresolved+1));fi;done; checked=$((checked+1));if is_active nfs-server.service;then active=$((active+1));nfs_active=1;if [ -r "${root}/etc/exports" ];then if grep -E '(^|[, (])no_root_squash([, )]|$)|(^|[, (])insecure([, )]|$)' "${root}/etc/exports" >/dev/null;then anonymous=$((anonymous+1));else restricted=$((restricted+1));fi;else unresolved=$((unresolved+1));fi;fi; checked=$((checked+1));if is_active smb.service||is_active smbd.service;then active=$((active+1));samba_active=1;if [ -r "${root}/etc/samba/smb.conf" ];then if grep -Eiq '^[[:space:]]*(guest ok|public)[[:space:]]*=[[:space:]]*(yes|true|1)' "${root}/etc/samba/smb.conf";then anonymous=$((anonymous+1));else restricted=$((restricted+1));fi;else unresolved=$((unresolved+1));fi;fi;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_SHARE_FILE:-}" ];then fixture "$OS_GUARD_TEST_SHARE_FILE";else runtime;fi;fi
if [ "$anonymous" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U35_ANONYMOUS_ACCESS_ENABLED;basis='Anonymous or guest access is enabled on an active sharing service'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U35_COLLECTION_FAILED;basis='Sharing service state or configuration could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"sharing service collection failed"}')
elif [ "$unresolved" -gt 0 ];then status_json=null;review_state=PENDING;reason=KISA_U35_POLICY_REVIEW_REQUIRED;basis='An active sharing service has unresolved anonymous access policy'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U35_ANONYMOUS_ACCESS_RESTRICTED;basis='No target sharing service is active or all active services restrict anonymous access';fi
printf '{"item_id":"U-35","status":%s,"review_state":"%s","current_value":{"service_checked_count":%s,"active_count":%s,"anonymous_enabled_count":%s,"restricted_count":%s,"unresolved_count":%s,"ftp_active":%s,"nfs_active":%s,"samba_active":%s,"collection_complete":%s},"evidence":{"item_id":"U-35","collection_method":"Read-only active FTP, NFS and Samba service and anonymous policy inspection","service_checked_count":%s,"active_count":%s,"anonymous_enabled_count":%s,"restricted_count":%s,"unresolved_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$checked" "$active" "$anonymous" "$restricted" "$unresolved" "$ftp_active" "$nfs_active" "$samba_active" "$complete" "$checked" "$active" "$anonymous" "$restricted" "$unresolved" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
