#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;active=0;approved=0;unapproved=0;unresolved=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked active approved unapproved unresolved extra < "$1"||true;case "$state" in complete)complete=true;;*)err=SERVICE_STATE_COLLECTION_FAILED;;esac;for v in "$checked" "$active" "$approved" "$unapproved" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ systemctl_bin=$(command -v systemctl 2>/dev/null||true);for u in rsh.socket rlogin.socket rexec.socket rsh.service rlogin.service rexec.service rsync.service rsyncd.service;do checked=$((checked+1));[ -n "$systemctl_bin" ]&&[ "$($systemctl_bin is-active "$u" 2>/dev/null||true)" = active ]&&active=$((active+1));done;for f in "${root}/etc/inetd.conf" "${root}/etc/xinetd.d/rsh" "${root}/etc/xinetd.d/rlogin" "${root}/etc/xinetd.d/rexec";do [ -r "$f" ]||continue;if grep -Eiq '^[[:space:]]*(rsh|shell|login|exec)[[:space:]]|disable[[:space:]]*=[[:space:]]*no' "$f";then active=$((active+1));fi;done;[ "$active" -gt 0 ]&&unresolved=$active;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_RSERVICE_FILE:-}" ];then fixture "$OS_GUARD_TEST_RSERVICE_FILE";else runtime;fi;fi
if [ "$unapproved" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U36_UNAPPROVED_RSERVICE_ACTIVE;basis='An active r-command service is verified as unnecessary'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U36_COLLECTION_FAILED;basis='r-command service activation could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"r-command service collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U36_ALL_INACTIVE;basis='No active r-command service was identified'
elif [ "$approved" -eq "$active" ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U36_ALL_LOCALLY_APPROVED;basis='All active related services have an approved operational purpose'
else status_json=null;review_state=PENDING;reason=KISA_U36_OPERATIONAL_PURPOSE_REVIEW;basis='Active r-command or related daemon use requires operational-purpose review';fi
printf '{"item_id":"U-36","status":%s,"review_state":"%s","current_value":{"service_checked_count":%s,"active_count":%s,"approved_count":%s,"unapproved_count":%s,"unresolved_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-36","collection_method":"Read-only systemd, inetd and xinetd activation inspection","service_checked_count":%s,"active_count":%s,"approved_count":%s,"unapproved_count":%s,"unresolved_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$checked" "$active" "$approved" "$unapproved" "$unresolved" "$complete" "$checked" "$active" "$approved" "$unapproved" "$unresolved" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
