#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;owner_bad=0;mode_bad=0;unresolved=0;missing_optional=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked owner_bad mode_bad unresolved missing_optional extra < "$1"||true;case "$state" in complete)complete=true;;*)err=METADATA_COLLECTION_FAILED;;esac;for v in "$checked" "$owner_bad" "$mode_bad" "$unresolved" "$missing_optional";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
inspect(){ path=$1;kind=$2;[ -e "$path" ]||{ missing_optional=$((missing_optional+1));return;};meta=$(stat -c '%u|%U|%a|%F' -- "$path" 2>/dev/null)||{ err=STAT_FAILED;return;};old=$IFS;IFS='|';set -- $meta;IFS=$old;[ "$#" -eq 4 ]||{ err=METADATA_PARSE_FAILED;return;};case "$1:$3" in *[!0-9:]*)err=METADATA_PARSE_FAILED;return;;esac;checked=$((checked+1));if [ "$1" -ne 0 ]||[ "$2" != root ];then owner_bad=$((owner_bad+1));fi;m=$((0$3));case "$kind" in executable)[ $((m & ~0750)) -eq 0 ]||mode_bad=$((mode_bad+1));;config|job)[ $((m & ~0640)) -eq 0 ]||mode_bad=$((mode_bad+1));;directory)[ $((m & 0002)) -eq 0 ]||mode_bad=$((mode_bad+1));;esac;case "$4" in *symbolic*)unresolved=$((unresolved+1));;esac;}
runtime(){ for p in "${root}/usr/bin/crontab" "${root}/usr/bin/at" "${root}/usr/bin/atq" "${root}/usr/bin/atrm";do inspect "$p" executable;done;for p in "${root}/etc/cron.allow" "${root}/etc/cron.deny" "${root}/etc/at.allow" "${root}/etc/at.deny" "${root}/etc/crontab";do inspect "$p" config;done;for p in "${root}/etc/cron.d" "${root}/var/spool/cron" "${root}/var/spool/cron/crontabs" "${root}/var/spool/at" "${root}/var/spool/atjobs";do inspect "$p" directory;done;[ -z "$err" ]&&complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_CRON_FILE:-}" ];then fixture "$OS_GUARD_TEST_CRON_FILE";else runtime;fi;fi
if [ "$owner_bad" -gt 0 ]||[ "$mode_bad" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U37_OWNER_OR_MODE_VIOLATION;basis='A cron or at executable, configuration, job, or spool target violates its metadata requirement'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U37_COLLECTION_FAILED;basis='Required cron or at metadata could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"cron and at metadata collection failed"}')
elif [ "$unresolved" -gt 0 ];then status_json=null;review_state=PENDING;reason=KISA_U37_PACKAGING_REVIEW;basis='A symbolic or nonstandard packaging layout requires review'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U37_METADATA_COMPLIANT;basis='All existing inspected cron and at targets satisfy their owner and permission class requirements';fi
printf '{"item_id":"U-37","status":%s,"review_state":"%s","current_value":{"checked_count":%s,"owner_violation_count":%s,"permission_violation_count":%s,"unresolved_count":%s,"missing_optional_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-37","collection_method":"Read-only stat metadata inspection with separate executable, configuration and spool criteria","checked_count":%s,"owner_violation_count":%s,"permission_violation_count":%s,"unresolved_count":%s,"missing_optional_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$checked" "$owner_bad" "$mode_bad" "$unresolved" "$missing_optional" "$complete" "$checked" "$owner_bad" "$mode_bad" "$unresolved" "$missing_optional" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
