#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;active=0;inactive=0;review=0;unapproved=0;legacy_active=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked active inactive review unapproved legacy_active extra < "$1"||true;case "$state" in complete)complete=true;;*)err=SERVICE_STATE_COLLECTION_FAILED;;esac;for v in "$checked" "$active" "$inactive" "$review" "$unapproved" "$legacy_active";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ systemctl_bin=$(command -v systemctl 2>/dev/null||true);for u in echo.socket discard.socket daytime.socket chargen.socket ntpd.service ntp.service chronyd.service snmpd.service named.service bind9.service;do checked=$((checked+1));if [ -n "$systemctl_bin" ]&&[ "$($systemctl_bin is-active "$u" 2>/dev/null||true)" = active ];then active=$((active+1));case "$u" in echo.*|discard.*|daytime.*|chargen.*)legacy_active=$((legacy_active+1));;*)review=$((review+1));;esac;else inactive=$((inactive+1));fi;done;for f in "${root}/etc/inetd.conf" "${root}/etc/xinetd.d/echo" "${root}/etc/xinetd.d/discard" "${root}/etc/xinetd.d/daytime" "${root}/etc/xinetd.d/chargen";do [ -r "$f" ]||continue;if grep -Eiq '^[[:space:]]*(echo|discard|daytime|chargen)[[:space:]]|disable[[:space:]]*=[[:space:]]*no' "$f";then active=$((active+1));legacy_active=$((legacy_active+1));fi;done;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_DOS_SERVICE_FILE:-}" ];then fixture "$OS_GUARD_TEST_DOS_SERVICE_FILE";else runtime;fi;fi
if [ "$unapproved" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U38_UNNECESSARY_SERVICE_ACTIVE;basis='An active DoS-prone service is verified as unnecessary by local policy'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U38_COLLECTION_FAILED;basis='DoS-prone service activation could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"DoS-prone service collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U38_ALL_INACTIVE;basis='No target DoS-prone service is active'
else status_json=null;review_state=PENDING;reason=KISA_U38_OPERATIONAL_PURPOSE_REVIEW;basis='Active legacy or infrastructure services require an operational-necessity decision';fi
printf '{"item_id":"U-38","status":%s,"review_state":"%s","current_value":{"service_checked_count":%s,"active_count":%s,"inactive_count":%s,"review_required_count":%s,"unapproved_count":%s,"legacy_active_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-38","collection_method":"Read-only systemd socket/service and inetd/xinetd activation inspection","service_checked_count":%s,"active_count":%s,"inactive_count":%s,"review_required_count":%s,"legacy_active_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$checked" "$active" "$inactive" "$review" "$unapproved" "$legacy_active" "$complete" "$checked" "$active" "$inactive" "$review" "$legacy_active" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
