#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);test_root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;present=0;active=0;inactive=0;unapproved=0;unresolved=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state present active inactive unapproved unresolved extra < "$1"||true;case "$state" in complete)complete=true;;*)err=SERVICE_STATE_COLLECTION_FAILED;;esac;for v in "$present" "$active" "$inactive" "$unapproved" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for u in nfs-server.service nfs.service rpc-statd.service nfs-mountd.service;do state=$($s is-active "$u" 2>/dev/null||true);case "$state" in active)present=$((present+1));active=$((active+1));;inactive|failed|unknown)inactive=$((inactive+1));;*)unresolved=$((unresolved+1));;esac;done;[ "$unresolved" -eq 4 ]&&{ err=SERVICE_QUERY_FAILED;return;};complete=true;[ "$active" -gt 0 ]&&unresolved=$active;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_NFS_FILE:-}" ];then fixture "$OS_GUARD_TEST_NFS_FILE";else runtime;fi;fi
if [ "$unapproved" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U39_UNAPPROVED_NFS_ACTIVE;basis='An active NFS daemon is verified as unnecessary'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U39_COLLECTION_FAILED;basis='NFS service state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"NFS service state collection failed"}')
elif [ "$active" -gt 0 ];then status_json=null;review_state=PENDING;reason=KISA_U39_OPERATIONAL_PURPOSE_REVIEW;basis='NFS is active and its operational necessity requires review'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U39_NFS_INACTIVE;basis='All bounded NFS server daemons are inactive';fi
printf '{"item_id":"U-39","status":%s,"review_state":"%s","current_value":{"nfs_present":%s,"active_daemon_count":%s,"inactive_daemon_count":%s,"review_required":%s,"collection_complete":%s},"evidence":{"item_id":"U-39","collection_method":"Read-only systemd NFS daemon state inspection","nfs_present":%s,"active_daemon_count":%s,"inactive_daemon_count":%s,"unresolved_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$present" "$active" "$inactive" "$unresolved" "$complete" "$present" "$active" "$inactive" "$unresolved" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
