#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;nfs_active=0;exports_exists=0;owner_ok=0;mode_ok=0;access_control=0;root_squash=0;broad=0;unresolved=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state nfs_active exports_exists owner_ok mode_ok access_control root_squash broad unresolved extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$nfs_active" "$exports_exists" "$owner_ok" "$mode_ok" "$access_control" "$root_squash" "$broad" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};state=$($s is-active nfs-server.service 2>/dev/null||true);case "$state" in active)nfs_active=1;;inactive|failed|unknown)nfs_active=0;;*)err=NFS_STATE_QUERY_FAILED;return;;esac;[ "$nfs_active" -eq 0 ]&&{ complete=true;return;};f="${root}/etc/exports";[ -r "$f" ]||{ err=EXPORTS_UNREADABLE;return;};exports_exists=1;meta=$(stat -c '%u|%U|%a' -- "$f" 2>/dev/null)||{ err=STAT_FAILED;return;};old=$IFS;IFS='|';set -- $meta;IFS=$old;[ "$#" -eq 3 ]||{ err=METADATA_PARSE_FAILED;return;};case "$1:$3" in *[!0-9:]*)err=METADATA_PARSE_FAILED;return;;esac;[ "$1" -eq 0 ]&&[ "$2" = root ]&&owner_ok=1;m=$((0$3));[ $((m & ~0644)) -eq 0 ]&&mode_ok=1;lines=$(grep -Ev '^[[:space:]]*(#|$)' "$f" 2>/dev/null||true);[ -n "$lines" ]||{ unresolved=$((unresolved+1));complete=true;return;};printf '%s\n' "$lines"|grep -Eq '[[:space:]]+[^[:space:]]+\('&&access_control=1;printf '%s\n' "$lines"|grep -Eq '(^|[, (])root_squash([, )]|$)'&&root_squash=1;printf '%s\n' "$lines"|grep -Eq '[[:space:]]+\*\('&&broad=1;[ "$broad" -gt 0 ]&&access_control=0;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_EXPORTS_FILE:-}" ];then fixture "$OS_GUARD_TEST_EXPORTS_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U40_COLLECTION_FAILED;basis='NFS state or exports metadata could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"NFS access-control collection failed"}')
elif [ "$nfs_active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U40_NFS_UNUSED;basis='NFS server service is inactive'
elif [ "$access_control" -eq 1 ]&&[ "$mode_ok" -eq 1 ]&&[ "$owner_ok" -eq 1 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U40_ACCESS_AND_MODE_COMPLIANT;basis='NFS access control is configured and exports metadata meets the 0644 subset requirement'
elif [ "$access_control" -eq 0 ]&&[ "$mode_ok" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U40_ACCESS_AND_MODE_VIOLATION;basis='NFS access control is absent and exports permission exceeds 0644'
else status_json=null;review_state=PENDING;reason=KISA_U40_MIXED_OR_POLICY_REVIEW;basis='The access-control and metadata combination does not exactly match the KISA GOOD or VULNERABLE sentence';fi
printf '{"item_id":"U-40","status":%s,"review_state":"%s","current_value":{"nfs_active":%s,"exports_exists":%s,"owner_compliant":%s,"permission_compliant":%s,"access_control_configured":%s,"root_squash_present":%s,"broad_export_detected":%s,"unresolved_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-40","collection_method":"Read-only NFS runtime, exports aggregate policy and stat metadata inspection","nfs_active":%s,"exports_exists":%s,"owner_compliant":%s,"permission_compliant":%s,"access_control_configured":%s,"root_squash_present":%s,"broad_export_detected":%s,"unresolved_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$nfs_active" "$exports_exists" "$owner_ok" "$mode_ok" "$access_control" "$root_squash" "$broad" "$unresolved" "$complete" "$nfs_active" "$exports_exists" "$owner_ok" "$mode_ok" "$access_control" "$root_squash" "$broad" "$unresolved" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
