#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;active=0;inactive=0;unresolved=0;complete=false;err='';targets='rpc.cmsd rpc.ttdbserverd sadmind rusersd walld sprayd rstatd rpc.nisd rexd rpc.pcnfsd rpc.statd rpc.ypupdated rpc.rquotad kcms_server cachefsd'
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked active inactive unresolved extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$checked" "$active" "$inactive" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for n in $targets;do checked=$((checked+1));state=$($s is-active "$n.service" 2>/dev/null||true);case "$state" in active)active=$((active+1));;inactive|failed|unknown)inactive=$((inactive+1));;*)unresolved=$((unresolved+1));;esac;done;for f in "${root}/etc/inetd.conf" "${root}"/etc/xinetd.d/*;do [ -r "$f" ]||continue;for n in $targets;do grep -Eiq "^[[:space:]]*$n[[:space:]]|service[[:space:]]+$n|disable[[:space:]]*=[[:space:]]*no" "$f"&&active=$((active+1));done;done;[ "$unresolved" -eq "$checked" ]&&{ err=SERVICE_QUERY_FAILED;return;};complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_RPC_FILE:-}" ];then fixture "$OS_GUARD_TEST_RPC_FILE";else runtime;fi;fi
if [ "$active" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U42_UNNECESSARY_RPC_ACTIVE;basis='At least one KISA-listed unnecessary RPC service is active'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U42_COLLECTION_FAILED;basis='RPC service states could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"RPC service state collection failed"}')
elif [ "$unresolved" -gt 0 ];then status_json=null;review_state=PENDING;reason=KISA_U42_MAPPING_REVIEW;basis='A nonstandard RPC service mapping requires review'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U42_ALL_INACTIVE;basis='All KISA-listed unnecessary RPC services are inactive';fi
printf '{"item_id":"U-42","status":%s,"review_state":"%s","current_value":{"checked_count":%s,"active_count":%s,"inactive_count":%s,"unresolved_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-42","collection_method":"Read-only exact KISA target inspection across systemd, inetd and xinetd","checked_count":%s,"active_count":%s,"inactive_count":%s,"unresolved_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$checked" "$active" "$inactive" "$unresolved" "$complete" "$checked" "$active" "$inactive" "$unresolved" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
