#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;active=0;inactive=0;unresolved=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked active inactive unresolved extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$checked" "$active" "$inactive" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for u in tftp.service tftp.socket tftpd.service talk.service talk.socket ntalk.service ntalk.socket;do checked=$((checked+1));state=$($s is-active "$u" 2>/dev/null||true);case "$state" in active)active=$((active+1));;inactive|failed|unknown)inactive=$((inactive+1));;*)unresolved=$((unresolved+1));;esac;done;for f in "${root}/etc/inetd.conf" "${root}"/etc/xinetd.d/tftp "${root}"/etc/xinetd.d/talk "${root}"/etc/xinetd.d/ntalk;do [ -r "$f" ]||continue;if grep -Eiq '^[[:space:]]*(tftp|talk|ntalk)[[:space:]]|disable[[:space:]]*=[[:space:]]*no' "$f";then active=$((active+1));fi;done;[ "$unresolved" -eq "$checked" ]&&{ err=SERVICE_QUERY_FAILED;return;};complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U44_FILE:-}" ];then fixture "$OS_GUARD_TEST_U44_FILE";else runtime;fi;fi
if [ "$active" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U44_SERVICE_ACTIVE;basis='At least one tftp, talk, or ntalk activation path is active'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U44_COLLECTION_FAILED;basis='Service activation state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"tftp and talk service state collection failed"}')
elif [ "$unresolved" -gt 0 ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U44_STATE_UNRESOLVED;basis='One or more target service states are unresolved';error_json='{"code":"SERVICE_STATE_UNRESOLVED","message":"target service state unresolved"}'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U44_ALL_INACTIVE;basis='All tftp, talk, and ntalk activation paths are inactive';fi
printf '{"item_id":"U-44","status":%s,"review_state":"%s","current_value":{"checked_count":%s,"active_count":%s,"inactive_count":%s,"unresolved_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-44","collection_method":"Read-only systemd service/socket and inetd/xinetd inspection","checked_count":%s,"active_count":%s,"inactive_count":%s,"unresolved_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$checked" "$active" "$inactive" "$unresolved" "$complete" "$checked" "$active" "$inactive" "$unresolved" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
