#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);test_root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;active=0;current=0;outdated=0;unknown=0;complete=false;err='';mta_type=none;version_known=0
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked active current outdated unknown mta_type version_known extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$checked" "$active" "$current" "$outdated" "$unknown" "$version_known";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for pair in postfix:postfix.service sendmail:sendmail.service exim:exim4.service;do name=${pair%%:*};unit=${pair#*:};checked=$((checked+1));state=$($s is-active "$unit" 2>/dev/null||true);case "$state" in active)active=$((active+1));mta_type=$name;;inactive|failed|unknown);;*)unknown=$((unknown+1));;esac;done;[ "$active" -eq 0 ]&&{ complete=true;return;};[ "$active" -gt 1 ]&&{ unknown=$((unknown+1));complete=true;return;};if [ "$distro" = rocky ];then dnf_bin=$(command -v dnf 2>/dev/null||true);[ -n "$dnf_bin" ]||{ unknown=$((unknown+1));complete=true;return;};$dnf_bin -q --cacheonly check-update "$mta_type" >/dev/null 2>&1;rc=$?;case "$rc" in 0)current=1;version_known=1;;100)outdated=1;version_known=1;;*)unknown=$((unknown+1));;esac;else apt_bin=$(command -v apt-get 2>/dev/null||true);[ -n "$apt_bin" ]||{ unknown=$((unknown+1));complete=true;return;};out=$($apt_bin -s --no-download install --only-upgrade "$mta_type" 2>/dev/null)||{ unknown=$((unknown+1));complete=true;return;};if printf '%s' "$out"|grep -q '^Inst ';then outdated=1;version_known=1;else current=1;version_known=1;fi;fi;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U45_FILE:-}" ];then fixture "$OS_GUARD_TEST_U45_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U45_COLLECTION_FAILED;basis='Mail service or local package update state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"mail version state collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U45_MAIL_UNUSED;basis='No target mail service is active'
elif [ "$outdated" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U45_LOCAL_UPDATE_AVAILABLE;basis='Trusted local package metadata identifies an update for the active mail service'
elif [ "$current" -gt 0 ]&&[ "$unknown" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U45_LOCAL_PACKAGE_CURRENT;basis='Trusted local package metadata reports the active mail package current'
else status_json=null;review_state=PENDING;reason=KISA_U45_LATEST_STATUS_UNKNOWN;basis='The active mail version was collected but latest status cannot be established from trusted local metadata';fi
printf '{"item_id":"U-45","status":%s,"review_state":"%s","current_value":{"service_checked_count":%s,"active_count":%s,"current_count":%s,"outdated_count":%s,"unknown_count":%s,"mta_type":' "$status_json" "$review_state" "$checked" "$active" "$current" "$outdated" "$unknown";os_guard_json_quote "$mta_type";printf ',"version_known":%s,"collection_complete":%s},"evidence":{"item_id":"U-45","collection_method":"Read-only active MTA and offline local package-cache update-state inspection","active_count":%s,"current_count":%s,"outdated_count":%s,"unknown_count":%s,"mta_type":' "$version_known" "$complete" "$active" "$current" "$outdated" "$unknown";os_guard_json_quote "$mta_type";printf ',"version_known":%s,"collection_complete":%s,"reason_code":' "$version_known" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
