#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;restricted=0;unrestricted=0;unresolved=0;complete=false;err='';mta=none
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active restricted unrestricted unresolved mta extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$active" "$restricted" "$unrestricted" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for pair in sendmail:sendmail.service postfix:postfix.service exim:exim4.service;do n=${pair%%:*};u=${pair#*:};[ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&{ active=$((active+1));mta=$n;};done;[ "$active" -eq 0 ]&&{ complete=true;return;};[ "$active" -eq 1 ]||{ unresolved=$((unresolved+1));complete=true;return;};case "$mta" in sendmail)f="${root}/etc/mail/sendmail.cf";[ -r "$f" ]||{ unresolved=1;complete=true;return;};grep -Eiq '^[[:space:]]*O[[:space:]]*PrivacyOptions=.*restrictqrun|^[[:space:]]*O[[:space:]]*PrivacyOptions[[:space:]]*=[^#]*restrictqrun' "$f"&&restricted=1||unrestricted=1;;postfix)p="${root}/usr/sbin/postsuper";[ -e "$p" ]||p="${root}/usr/bin/postsuper";[ -e "$p" ]||{ unresolved=1;complete=true;return;};mode=$(stat -c '%a' -- "$p" 2>/dev/null)||{ err=STAT_FAILED;return;};case "$mode" in *[!0-7]*)err=MODE_PARSE_FAILED;return;;esac;m=$((0$mode));[ $((m&0001)) -eq 0 ]&&restricted=1||unrestricted=1;;exim)p="${root}/usr/sbin/exiqgrep";[ -e "$p" ]||p="${root}/usr/bin/exiqgrep";[ -e "$p" ]||{ unresolved=1;complete=true;return;};mode=$(stat -c '%a' -- "$p" 2>/dev/null)||{ err=STAT_FAILED;return;};m=$((0$mode));[ $((m&0001)) -eq 0 ]&&restricted=1||unrestricted=1;;esac;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U46_FILE:-}" ];then fixture "$OS_GUARD_TEST_U46_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U46_COLLECTION_FAILED;basis='Mail service restriction state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"mail execution restriction collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U46_MAIL_UNUSED;basis='No target SMTP service is active'
elif [ "$unrestricted" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U46_GENERAL_EXECUTION_ALLOWED;basis='The active MTA does not restrict the applicable general-user queue operation'
elif [ "$restricted" -gt 0 ]&&[ "$unresolved" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U46_EXECUTION_RESTRICTED;basis='The active MTA restricts the applicable general-user queue operation'
else status_json=null;review_state=PENDING;reason=KISA_U46_MTA_POLICY_UNRESOLVED;basis='The effective MTA execution restriction cannot be established safely';fi
printf '{"item_id":"U-46","status":%s,"review_state":"%s","current_value":{"active_count":%s,"restricted_count":%s,"unrestricted_count":%s,"unresolved_count":%s,"mta_type":' "$status_json" "$review_state" "$active" "$restricted" "$unrestricted" "$unresolved";os_guard_json_quote "$mta";printf ',"collection_complete":%s},"evidence":{"item_id":"U-46","collection_method":"Read-only active MTA configuration or administrative executable metadata inspection","active_count":%s,"restricted_count":%s,"unrestricted_count":%s,"unresolved_count":%s,"mta_type":' "$complete" "$active" "$restricted" "$unrestricted" "$unresolved";os_guard_json_quote "$mta";printf ',"collection_complete":%s,"reason_code":' "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
