#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;restricted=0;open_relay=0;unresolved=0;complete=false;err='';mta=none
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active restricted open_relay unresolved mta extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$active" "$restricted" "$open_relay" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for pair in sendmail:sendmail.service postfix:postfix.service exim:exim4.service;do n=${pair%%:*};u=${pair#*:};[ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&{ active=$((active+1));mta=$n;};done;[ "$active" -eq 0 ]&&{ complete=true;return;};[ "$active" -eq 1 ]||{ unresolved=1;complete=true;return;};case "$mta" in sendmail)f="${root}/etc/mail/sendmail.cf";[ -r "$f" ]||{ unresolved=1;complete=true;return;};grep -Eiq 'promiscuous_relay' "$f"&&open_relay=1||{ grep -Eiq 'access_db|relay_hosts_only|relay_entire_domain' "$f"&&restricted=1||unresolved=1; };;postfix)f="${root}/etc/postfix/main.cf";[ -r "$f" ]||{ unresolved=1;complete=true;return;};if grep -Eiq '^[[:space:]]*smtpd_(relay|recipient)_restrictions[[:space:]]*=.*(reject_unauth_destination|defer_unauth_destination)' "$f";then restricted=1;elif grep -Eiq '^[[:space:]]*smtpd_(relay|recipient)_restrictions[[:space:]]*=[[:space:]]*$' "$f";then open_relay=1;else unresolved=1;fi;;exim)f="${root}/etc/exim4/exim4.conf.template";[ -r "$f" ]||{ unresolved=1;complete=true;return;};grep -Eiq 'relay_from_hosts|hostlist[[:space:]]+relay_from_hosts|deny[[:space:]]+message.*relay' "$f"&&restricted=1||unresolved=1;;esac;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U47_FILE:-}" ];then fixture "$OS_GUARD_TEST_U47_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U47_COLLECTION_FAILED;basis='SMTP relay control could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"SMTP relay restriction collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U47_MAIL_UNUSED;basis='No target SMTP service is active'
elif [ "$open_relay" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U47_RELAY_UNRESTRICTED;basis='The active SMTP service has an explicitly unrestricted relay policy'
elif [ "$restricted" -gt 0 ]&&[ "$unresolved" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U47_RELAY_RESTRICTED;basis='The active SMTP service has an effective relay restriction'
else status_json=null;review_state=PENDING;reason=KISA_U47_EFFECTIVE_POLICY_UNRESOLVED;basis='Dynamic, included, or incomplete MTA settings prevent reliable relay-policy evaluation';fi
printf '{"item_id":"U-47","status":%s,"review_state":"%s","current_value":{"active_count":%s,"restricted_count":%s,"open_relay_count":%s,"unresolved_count":%s,"mta_type":' "$status_json" "$review_state" "$active" "$restricted" "$open_relay" "$unresolved";os_guard_json_quote "$mta";printf ',"collection_complete":%s},"evidence":{"item_id":"U-47","collection_method":"Read-only active MTA aggregate relay-policy inspection","active_count":%s,"restricted_count":%s,"open_relay_count":%s,"unresolved_count":%s,"mta_type":' "$complete" "$active" "$restricted" "$open_relay" "$unresolved";os_guard_json_quote "$mta";printf ',"collection_complete":%s,"reason_code":' "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
