#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;expn_blocked=0;vrfy_blocked=0;unresolved=0;complete=false;err='';mta=none
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active expn_blocked vrfy_blocked unresolved mta extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$active" "$expn_blocked" "$vrfy_blocked" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for pair in sendmail:sendmail.service postfix:postfix.service exim:exim4.service;do n=${pair%%:*};u=${pair#*:};[ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&{ active=$((active+1));mta=$n;};done;[ "$active" -eq 0 ]&&{ complete=true;return;};[ "$active" -eq 1 ]||{ unresolved=1;complete=true;return;};case "$mta" in sendmail)f="${root}/etc/mail/sendmail.cf";[ -r "$f" ]||{ unresolved=1;complete=true;return;};opts=$(grep -Ei '^[[:space:]]*O[[:space:]]*PrivacyOptions' "$f"|tail -n 1);printf '%s' "$opts"|grep -Eiq 'goaway|noexpn'&&expn_blocked=1;printf '%s' "$opts"|grep -Eiq 'goaway|novrfy'&&vrfy_blocked=1;;postfix)f="${root}/etc/postfix/main.cf";[ -r "$f" ]||{ unresolved=1;complete=true;return;};grep -Eiq '^[[:space:]]*disable_vrfy_command[[:space:]]*=[[:space:]]*yes' "$f"&&{ vrfy_blocked=1;expn_blocked=1; }||unresolved=1;;exim)f="${root}/etc/exim4/exim4.conf.template";[ -r "$f" ]||{ unresolved=1;complete=true;return;};grep -Eiq 'acl_smtp_expn' "$f"&&expn_blocked=1||unresolved=$((unresolved+1));grep -Eiq 'acl_smtp_vrfy' "$f"&&vrfy_blocked=1||unresolved=$((unresolved+1));;esac;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U48_FILE:-}" ];then fixture "$OS_GUARD_TEST_U48_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U48_COLLECTION_FAILED;basis='EXPN/VRFY restriction state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"EXPN and VRFY restriction collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U48_MAIL_UNUSED;basis='No target SMTP service is active'
elif [ "$expn_blocked" -eq 1 ]&&[ "$vrfy_blocked" -eq 1 ]&&[ "$unresolved" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U48_COMMANDS_BLOCKED;basis='Both EXPN and VRFY information-disclosure commands are restricted'
elif [ "$mta" = sendmail ]&&{ [ "$expn_blocked" -eq 0 ]||[ "$vrfy_blocked" -eq 0 ]; };then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U48_SENDMAIL_OPTION_MISSING;basis='The active Sendmail PrivacyOptions do not contain both noexpn and novrfy or goaway'
else status_json=null;review_state=PENDING;reason=KISA_U48_EFFECTIVE_POLICY_UNRESOLVED;basis='The active non-Sendmail or dynamic MTA policy cannot be mapped safely to both restrictions';fi
printf '{"item_id":"U-48","status":%s,"review_state":"%s","current_value":{"active_count":%s,"expn_blocked":%s,"vrfy_blocked":%s,"unresolved_count":%s,"mta_type":' "$status_json" "$review_state" "$active" "$expn_blocked" "$vrfy_blocked" "$unresolved";os_guard_json_quote "$mta";printf ',"collection_complete":%s},"evidence":{"item_id":"U-48","collection_method":"Read-only active MTA EXPN and VRFY aggregate restriction inspection","active_count":%s,"expn_blocked":%s,"vrfy_blocked":%s,"unresolved_count":%s,"mta_type":' "$complete" "$active" "$expn_blocked" "$vrfy_blocked" "$unresolved";os_guard_json_quote "$mta";printf ',"collection_complete":%s,"reason_code":' "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
