#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);test_root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;current=0;outdated=0;unknown=0;version_known=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active current outdated unknown version_known extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$active" "$current" "$outdated" "$unknown" "$version_known";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};state=$($s is-active named.service 2>/dev/null||true);[ "$state" = active ]||state=$($s is-active bind9.service 2>/dev/null||true);case "$state" in active)active=1;;inactive|failed|unknown)complete=true;return;;*)err=DNS_STATE_QUERY_FAILED;return;;esac;if [ "$distro" = rocky ];then d=$(command -v dnf 2>/dev/null||true);[ -n "$d" ]||{ unknown=1;complete=true;return;};$d -q --cacheonly check-update bind bind-utils >/dev/null 2>&1;rc=$?;case "$rc" in 0)current=1;version_known=1;;100)outdated=1;version_known=1;;*)unknown=1;;esac;else a=$(command -v apt-get 2>/dev/null||true);[ -n "$a" ]||{ unknown=1;complete=true;return;};out=$($a -s --no-download install --only-upgrade bind9 2>/dev/null)||{ unknown=1;complete=true;return;};if printf '%s' "$out"|grep -q '^Inst ';then outdated=1;else current=1;fi;version_known=1;fi;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U49_FILE:-}" ];then fixture "$OS_GUARD_TEST_U49_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U49_COLLECTION_FAILED;basis='BIND runtime or local package update state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"BIND update-state collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U49_DNS_UNUSED;basis='BIND/named is inactive'
elif [ "$outdated" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U49_LOCAL_UPDATE_AVAILABLE;basis='Trusted local package metadata identifies an update for active BIND'
elif [ "$current" -gt 0 ]&&[ "$unknown" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U49_LOCAL_PACKAGE_CURRENT;basis='Trusted local package metadata reports active BIND current'
else status_json=null;review_state=PENDING;reason=KISA_U49_PATCH_STATUS_UNKNOWN;basis='BIND is active but security update status cannot be established from trusted local metadata';fi
printf '{"item_id":"U-49","status":%s,"review_state":"%s","current_value":{"dns_active":%s,"current_count":%s,"outdated_count":%s,"unknown_count":%s,"version_known":%s,"collection_complete":%s},"evidence":{"item_id":"U-49","collection_method":"Read-only BIND runtime and offline local package-cache update-state inspection","dns_active":%s,"current_count":%s,"outdated_count":%s,"unknown_count":%s,"version_known":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$active" "$current" "$outdated" "$unknown" "$version_known" "$complete" "$active" "$current" "$outdated" "$unknown" "$version_known" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
