#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;restricted=0;unrestricted=0;include_count=0;unresolved=0;checked=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active restricted unrestricted include_count unresolved checked extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$active" "$restricted" "$unrestricted" "$include_count" "$unresolved" "$checked";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
scan(){ f=$1;[ -r "$f" ]||return;checked=$((checked+1));grep -Eiq '^[[:space:]]*include[[:space:]]' "$f"&&include_count=$((include_count+1));if grep -Eiq 'allow-transfer[[:space:]]*\{[[:space:]]*(any|0\.0\.0\.0/0|::/0)[[:space:]]*;' "$f";then unrestricted=$((unrestricted+1));elif grep -Eiq 'allow-transfer[[:space:]]*\{[[:space:]]*none[[:space:]]*;|allow-transfer[[:space:]]*\{[^}]+;' "$f";then restricted=$((restricted+1));else unresolved=$((unresolved+1));fi;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};state=$($s is-active named.service 2>/dev/null||true);[ "$state" = active ]||state=$($s is-active bind9.service 2>/dev/null||true);case "$state" in active)active=1;;inactive|failed|unknown)complete=true;return;;*)err=DNS_STATE_QUERY_FAILED;return;;esac;for f in "${root}/etc/named.conf" "${root}"/etc/bind/named.conf*;do [ -e "$f" ]&&scan "$f";done;[ "$checked" -gt 0 ]||{ err=DNS_CONFIG_UNREADABLE;return;};[ "$include_count" -gt 0 ]&&unresolved=$((unresolved+include_count));complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U50_FILE:-}" ];then fixture "$OS_GUARD_TEST_U50_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U50_COLLECTION_FAILED;basis='DNS runtime or transfer policy could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"DNS zone-transfer collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U50_DNS_UNUSED;basis='BIND/named is inactive'
elif [ "$unrestricted" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U50_TRANSFER_UNRESTRICTED;basis='Zone transfer is explicitly allowed to any source'
elif [ "$restricted" -gt 0 ]&&[ "$unresolved" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U50_TRANSFER_RESTRICTED;basis='Zone transfer is disabled or restricted to bounded principals'
else status_json=null;review_state=PENDING;reason=KISA_U50_EFFECTIVE_POLICY_UNRESOLVED;basis='Include, ACL, legacy, or zone-specific policy prevents reliable effective transfer evaluation';fi
printf '{"item_id":"U-50","status":%s,"review_state":"%s","current_value":{"dns_active":%s,"restricted_count":%s,"unrestricted_count":%s,"include_count":%s,"unresolved_count":%s,"checked_config_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-50","collection_method":"Read-only aggregate BIND allow-transfer inspection","dns_active":%s,"restricted_count":%s,"unrestricted_count":%s,"include_count":%s,"unresolved_count":%s,"checked_config_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$active" "$restricted" "$unrestricted" "$include_count" "$unresolved" "$checked" "$complete" "$active" "$restricted" "$unrestricted" "$include_count" "$unresolved" "$checked" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
