#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;disabled=0;restricted=0;unrestricted=0;complex=0;checked=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active disabled restricted unrestricted complex checked extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$active" "$disabled" "$restricted" "$unrestricted" "$complex" "$checked";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
scan(){ f=$1;[ -r "$f" ]||return;checked=$((checked+1));grep -Eiq '^[[:space:]]*include[[:space:]]' "$f"&&complex=$((complex+1));if grep -Eiq 'allow-update[[:space:]]*\{[[:space:]]*none[[:space:]]*;' "$f";then disabled=$((disabled+1));elif grep -Eiq 'allow-update[[:space:]]*\{[[:space:]]*(any|0\.0\.0\.0/0|::/0)[[:space:]]*;' "$f";then unrestricted=$((unrestricted+1));elif grep -Eiq 'allow-update[[:space:]]*\{[^}]+;|update-policy[[:space:]]' "$f";then restricted=$((restricted+1));fi;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};state=$($s is-active named.service 2>/dev/null||true);[ "$state" = active ]||state=$($s is-active bind9.service 2>/dev/null||true);case "$state" in active)active=1;;inactive|failed|unknown)complete=true;return;;*)err=DNS_STATE_QUERY_FAILED;return;;esac;for f in "${root}/etc/named.conf" "${root}"/etc/bind/named.conf*;do [ -e "$f" ]&&scan "$f";done;[ "$checked" -gt 0 ]||{ err=DNS_CONFIG_UNREADABLE;return;};complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U51_FILE:-}" ];then fixture "$OS_GUARD_TEST_U51_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U51_COLLECTION_FAILED;basis='DNS runtime or dynamic-update policy could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"DNS dynamic-update collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U51_DNS_UNUSED;basis='BIND/named is inactive'
elif [ "$unrestricted" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U51_UPDATE_UNRESTRICTED;basis='Dynamic update is explicitly allowed to any source'
elif [ "$disabled" -gt 0 ]&&[ "$unrestricted" -eq 0 ]&&[ "$complex" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U51_UPDATE_DISABLED;basis='Dynamic update is explicitly disabled'
elif [ "$restricted" -gt 0 ]&&[ "$unrestricted" -eq 0 ]&&[ "$complex" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U51_UPDATE_RESTRICTED;basis='Dynamic update has explicit bounded access control'
else status_json=null;review_state=PENDING;reason=KISA_U51_EFFECTIVE_POLICY_UNRESOLVED;basis='ACL, include, TSIG, update-policy, or zone-specific configuration requires effective-policy review';fi
printf '{"item_id":"U-51","status":%s,"review_state":"%s","current_value":{"dns_active":%s,"disabled_count":%s,"restricted_count":%s,"unrestricted_count":%s,"complex_count":%s,"checked_config_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-51","collection_method":"Read-only aggregate BIND allow-update and update-policy inspection","dns_active":%s,"disabled_count":%s,"restricted_count":%s,"unrestricted_count":%s,"complex_count":%s,"checked_config_count":%s,"collection_complete":%s,"reason_code":' "$status_json" "$review_state" "$active" "$disabled" "$restricted" "$unrestricted" "$complex" "$checked" "$complete" "$active" "$disabled" "$restricted" "$unrestricted" "$complex" "$checked" "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
