#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;banner_configured=0;product_exposed=0;safe=0;unresolved=0;complete=false;err='';server=none
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active banner_configured product_exposed safe unresolved server extra < "$1"||true;case "$state" in complete)complete=true;;*)err=COLLECTION_FAILED;;esac;for v in "$active" "$banner_configured" "$product_exposed" "$safe" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for pair in vsftpd:vsftpd.service proftpd:proftpd.service;do n=${pair%%:*};u=${pair#*:};[ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&{ active=$((active+1));server=$n;};done;[ "$active" -eq 0 ]&&{ complete=true;return;};[ "$active" -eq 1 ]||{ unresolved=1;complete=true;return;};case "$server" in vsftpd)f="${root}/etc/vsftpd/vsftpd.conf";[ -r "$f" ]||f="${root}/etc/vsftpd.conf";[ -r "$f" ]||{ err=FTP_CONFIG_UNREADABLE;return;};if grep -Eiq '^[[:space:]]*ftpd_banner[[:space:]]*=' "$f";then banner_configured=1;value=$(grep -Ei '^[[:space:]]*ftpd_banner[[:space:]]*=' "$f"|tail -n1);if printf '%s' "$value"|grep -Eiq '(vsftpd|ftp[[:space:]]+server|version|[0-9]+\.[0-9]+)';then product_exposed=1;else safe=1;fi;else unresolved=1;fi;;proftpd)f="${root}/etc/proftpd/proftpd.conf";[ -r "$f" ]||{ err=FTP_CONFIG_UNREADABLE;return;};if grep -Eiq '^[[:space:]]*ServerIdent[[:space:]]+off' "$f";then banner_configured=1;safe=1;elif grep -Eiq '^[[:space:]]*ServerIdent[[:space:]]+on' "$f";then banner_configured=1;product_exposed=1;else unresolved=1;fi;;esac;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U53_FILE:-}" ];then fixture "$OS_GUARD_TEST_U53_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U53_COLLECTION_FAILED;basis='FTP runtime or banner configuration could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"FTP banner collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U53_FTP_UNUSED;basis='No target FTP service is active'
elif [ "$product_exposed" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U53_PRODUCT_INFO_EXPOSED;basis='The active FTP banner explicitly exposes product or version information'
elif [ "$safe" -gt 0 ]&&[ "$unresolved" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U53_BANNER_RESTRICTED;basis='The active FTP service suppresses or replaces product-identifying banner information'
else status_json=null;review_state=PENDING;reason=KISA_U53_BANNER_EFFECT_UNRESOLVED;basis='A custom, included, or nonstandard FTP banner cannot be classified safely';fi
printf '{"item_id":"U-53","status":%s,"review_state":"%s","current_value":{"active_count":%s,"banner_configured":%s,"product_info_exposed":%s,"safe_banner_count":%s,"unresolved_count":%s,"server_type":' "$status_json" "$review_state" "$active" "$banner_configured" "$product_exposed" "$safe" "$unresolved";os_guard_json_quote "$server";printf ',"collection_complete":%s},"evidence":{"item_id":"U-53","collection_method":"Read-only active FTP service and aggregate banner-policy inspection","active_count":%s,"banner_configured":%s,"product_info_exposed":%s,"safe_banner_count":%s,"unresolved_count":%s,"server_type":' "$complete" "$active" "$banner_configured" "$product_exposed" "$safe" "$unresolved";os_guard_json_quote "$server";printf ',"collection_complete":%s,"reason_code":' "$complete";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
