#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;active=0;plain=0;tls_forced=0;unresolved=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked active plain tls_forced unresolved extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$checked" "$active" "$plain" "$tls_forced" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
yes_setting(){ grep -Eiq "^[[:space:]]*$2[[:space:]]*=[[:space:]]*YES([[:space:]]*(#.*)?)?$" "$1"; }
no_setting(){ grep -Eiq "^[[:space:]]*$2[[:space:]]*=[[:space:]]*NO([[:space:]]*(#.*)?)?$" "$1"; }
classify_vsftpd(){ f="${root}/etc/vsftpd/vsftpd.conf";[ -r "$f" ]||f="${root}/etc/vsftpd.conf";[ -r "$f" ]||{ unresolved=$((unresolved+1));return;};if no_setting "$f" ssl_enable||no_setting "$f" force_local_logins_ssl||no_setting "$f" force_local_data_ssl;then plain=$((plain+1));elif yes_setting "$f" ssl_enable&&yes_setting "$f" force_local_logins_ssl&&yes_setting "$f" force_local_data_ssl;then if yes_setting "$f" anonymous_enable;then if yes_setting "$f" force_anon_logins_ssl&&yes_setting "$f" force_anon_data_ssl;then tls_forced=$((tls_forced+1));else unresolved=$((unresolved+1));fi;else tls_forced=$((tls_forced+1));fi;else unresolved=$((unresolved+1));fi;}
classify_proftpd(){ f="${root}/etc/proftpd/proftpd.conf";[ -r "$f" ]||{ unresolved=$((unresolved+1));return;};if grep -Eiq '^[[:space:]]*Include[[:space:]]' "$f";then unresolved=$((unresolved+1));elif grep -Eiq '^[[:space:]]*TLSEngine[[:space:]]+on' "$f"&&grep -Eiq '^[[:space:]]*TLSRequired[[:space:]]+on' "$f";then tls_forced=$((tls_forced+1));elif grep -Eiq '^[[:space:]]*(TLSEngine[[:space:]]+off|TLSRequired[[:space:]]+off)' "$f";then plain=$((plain+1));else unresolved=$((unresolved+1));fi;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for pair in vsftpd:vsftpd.service proftpd:proftpd.service generic:ftp.service generic:ftp.socket;do kind=${pair%%:*};unit=${pair#*:};checked=$((checked+1));state=$($s is-active "$unit" 2>/dev/null||true);case "$state" in active)active=$((active+1));case "$kind" in vsftpd)classify_vsftpd;;proftpd)classify_proftpd;;*)unresolved=$((unresolved+1));;esac;;inactive|failed|unknown);;*)unresolved=$((unresolved+1));;esac;done;for f in "${root}/etc/inetd.conf" "${root}/etc/xinetd.d/ftp";do [ -r "$f" ]||continue;if grep -Eiq '^[[:space:]]*ftp[[:space:]]|disable[[:space:]]*=[[:space:]]*no' "$f";then active=$((active+1));plain=$((plain+1));fi;done;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U54_FILE:-}" ];then fixture "$OS_GUARD_TEST_U54_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U54_COLLECTION_FAILED;basis='FTP runtime or transport-security state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"FTP transport state collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U54_PLAIN_FTP_INACTIVE;basis='No plaintext FTP activation path is active'
elif [ "$plain" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U54_PLAIN_FTP_ACTIVE;basis='An active FTP path permits unencrypted FTP'
elif [ "$tls_forced" -eq "$active" ]&&[ "$unresolved" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U54_TLS_FORCED;basis='Every active FTP daemon has transport encryption explicitly forced'
else status_json=null;review_state=PENDING;reason=KISA_U54_TRANSPORT_UNRESOLVED;basis='The active FTP transport mode cannot be classified safely';fi
printf '{"item_id":"U-54","status":%s,"review_state":"%s","current_value":{"checked_count":%s,"active_count":%s,"plaintext_active_count":%s,"tls_forced_count":%s,"unresolved_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-54","collection_method":"Read-only FTP runtime and TLS-enforcement inspection","active_count":%s,"plaintext_active_count":%s,"tls_forced_count":%s,"unresolved_count":%s,"reason_code":' "$status_json" "$review_state" "$checked" "$active" "$plain" "$tls_forced" "$unresolved" "$complete" "$active" "$plain" "$tls_forced" "$unresolved";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
