#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;passwd_checked=0;valid=0;malformed=0;account_present=0;restricted=0;login_shell=0;service_active=0;service_known=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state passwd_checked valid malformed account_present restricted login_shell service_active service_known extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$passwd_checked" "$valid" "$malformed" "$account_present" "$restricted" "$login_shell" "$service_active" "$service_known";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ f="${root}/etc/passwd";[ -r "$f" ]||{ err=PASSWD_UNREADABLE;return;};[ -s "$f" ]||{ err=PASSWD_EMPTY;return;};passwd_checked=1;while IFS=: read -r name pw uid gid gecos home shell extra;do if [ -n "${extra:-}" ]||[ -z "$name" ]||[ -z "$uid" ]||[ -z "$gid" ]||[ -z "$shell" ];then malformed=$((malformed+1));continue;fi;valid=$((valid+1));if [ "$name" = ftp ];then account_present=1;case "$shell" in /bin/false|/sbin/nologin|/usr/sbin/nologin)restricted=1;;*)login_shell=1;;esac;fi;done < "$f";[ "$valid" -gt 0 ]||{ err=PASSWD_PARSE_FAILED;return;};[ "$malformed" -eq 0 ]||{ err=PASSWD_PARSE_FAILED;return;};s=$(command -v systemctl 2>/dev/null||true);if [ -n "$s" ];then service_known=1;for u in vsftpd.service proftpd.service ftp.service ftp.socket;do [ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&service_active=$((service_active+1));done;fi;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U55_FILE:-}" ];then fixture "$OS_GUARD_TEST_U55_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U55_COLLECTION_FAILED;basis='The local passwd account structure could not be validated';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"FTP account shell collection failed"}')
elif [ "$account_present" -gt 0 ]&&[ "$restricted" -gt 0 ]&&[ "$login_shell" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U55_SHELL_RESTRICTED;basis='The local FTP account uses an explicit non-login shell'
elif [ "$account_present" -gt 0 ]&&[ "$login_shell" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U55_LOGIN_SHELL_ASSIGNED;basis='The local FTP account has a shell that is not an approved non-login shell'
elif [ "$account_present" -eq 0 ]&&[ "$service_known" -gt 0 ]&&[ "$service_active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U55_ACCOUNT_AND_SERVICE_ABSENT;basis='No local FTP account exists and no target FTP service is active'
else status_json=null;review_state=PENDING;reason=KISA_U55_ACCOUNT_SOURCE_UNRESOLVED;basis='An active or nonstandard FTP account source cannot be resolved from local passwd data';fi
printf '{"item_id":"U-55","status":%s,"review_state":"%s","current_value":{"passwd_checked":%s,"valid_entry_count":%s,"malformed_entry_count":%s,"ftp_account_present":%s,"shell_restricted":%s,"login_shell_count":%s,"service_active_count":%s},"evidence":{"item_id":"U-55","collection_method":"Read-only local passwd FTP-account shell inspection","passwd_checked":%s,"ftp_account_present":%s,"shell_restricted":%s,"service_active_count":%s,"reason_code":' "$status_json" "$review_state" "$passwd_checked" "$valid" "$malformed" "$account_present" "$restricted" "$login_shell" "$service_active" "$passwd_checked" "$account_present" "$restricted" "$service_active";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
