#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;control=0;targets=0;none=0;complex=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active control targets none complex extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$active" "$control" "$targets" "$none" "$complex";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};kind=none;for pair in vsftpd:vsftpd.service proftpd:proftpd.service ftp:ftp.service ftp:ftp.socket;do n=${pair%%:*};u=${pair#*:};if [ "$($s is-active "$u" 2>/dev/null||true)" = active ];then active=$((active+1));[ "$kind" = none ]&&kind=$n||kind=mixed;fi;done;[ "$active" -eq 0 ]&&{ complete=true;return;};[ "$kind" != mixed ]||{ complex=1;complete=true;return;};case "$kind" in vsftpd)f="${root}/etc/vsftpd/vsftpd.conf";[ -r "$f" ]||f="${root}/etc/vsftpd.conf";[ -r "$f" ]||{ err=FTP_CONFIG_UNREADABLE;return;};if grep -Eiq '^[[:space:]]*(include|include_dir)[[:space:]]*=' "$f";then complex=1;elif grep -Eiq '^[[:space:]]*tcp_wrappers[[:space:]]*=[[:space:]]*YES' "$f";then a="${root}/etc/hosts.allow";d="${root}/etc/hosts.deny";if [ -r "$a" ]&&[ -r "$d" ]&&grep -Eiq '^[[:space:]]*(vsftpd|ftpd)[[:space:]]*:[[:space:]]*[^[:space:]#]' "$a"&&grep -Eiq '^[[:space:]]*(vsftpd|ftpd|ALL)[[:space:]]*:[[:space:]]*ALL' "$d";then control=1;targets=1;else complex=1;fi;else none=1;fi;;proftpd)f="${root}/etc/proftpd/proftpd.conf";[ -r "$f" ]||{ err=FTP_CONFIG_UNREADABLE;return;};if grep -Eiq '^[[:space:]]*Include[[:space:]]' "$f";then complex=1;elif grep -Eiq '^[[:space:]]*Allow[[:space:]]+from[[:space:]]+[^[:space:]#]+' "$f"&&grep -Eiq '^[[:space:]]*DenyAll' "$f";then control=1;targets=1;else none=1;fi;;*)complex=1;;esac;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U56_FILE:-}" ];then fixture "$OS_GUARD_TEST_U56_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U56_COLLECTION_FAILED;basis='FTP service or access-control state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"FTP access-control collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U56_FTP_INACTIVE;basis='No target FTP service is active'
elif [ "$control" -gt 0 ]&&[ "$targets" -gt 0 ]&&[ "$complex" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U56_HOST_RESTRICTION_PRESENT;basis='The active FTP daemon has an explicit host-based allow restriction'
elif [ "$none" -gt 0 ]&&[ "$complex" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U56_ACCESS_CONTROL_ABSENT;basis='The active FTP daemon has no local host-based access restriction'
else status_json=null;review_state=PENDING;reason=KISA_U56_ACCESS_SCOPE_UNRESOLVED;basis='External ACL, firewall, include, or mixed-daemon policy prevents a safe local conclusion';fi
printf '{"item_id":"U-56","status":%s,"review_state":"%s","current_value":{"active_count":%s,"access_control_present":%s,"restricted_target_count":%s,"no_control_count":%s,"complex_policy_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-56","collection_method":"Read-only active FTP daemon and aggregate host-access policy inspection","active_count":%s,"access_control_present":%s,"restriction_type":"host_based","restricted_target_count":%s,"complex_policy_count":%s,"reason_code":' "$status_json" "$review_state" "$active" "$control" "$targets" "$none" "$complex" "$complete" "$active" "$control" "$targets" "$complex";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
