#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;blocked=0;allowed=0;unresolved=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active blocked allowed unresolved extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$active" "$blocked" "$allowed" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
has_root(){ [ -r "$1" ]&&grep -Eq '^[[:space:]]*root[[:space:]]*(#.*)?$' "$1"; }
classify_vsftpd(){ f="${root}/etc/vsftpd/vsftpd.conf";[ -r "$f" ]||f="${root}/etc/vsftpd.conf";[ -r "$f" ]||{ err=FTP_CONFIG_UNREADABLE;return;};if grep -Eiq '^[[:space:]]*(include|include_dir)[[:space:]]*=' "$f";then unresolved=$((unresolved+1));return;fi;candidate_allowed=0;list="${root}/etc/vsftpd/user_list";custom=$(grep -Ei '^[[:space:]]*userlist_file[[:space:]]*=' "$f"|tail -n1|cut -d= -f2-|tr -d '[:space:]');[ -z "$custom" ]||list="${root}${custom}";if grep -Eiq '^[[:space:]]*userlist_enable[[:space:]]*=[[:space:]]*YES' "$f";then if grep -Eiq '^[[:space:]]*userlist_deny[[:space:]]*=[[:space:]]*NO' "$f";then if has_root "$list";then candidate_allowed=1;else blocked=$((blocked+1));return;fi;elif has_root "$list";then blocked=$((blocked+1));return;fi;fi;pam="${root}/etc/pam.d/vsftpd";if [ -r "$pam" ]&&grep -Eiq 'pam_listfile\.so.*sense=deny.*file=/etc/(ftpusers|ftpd/ftpusers)' "$pam";then pf="${root}/etc/ftpusers";[ -r "${root}/etc/ftpd/ftpusers" ]&&pf="${root}/etc/ftpd/ftpusers";if has_root "$pf";then blocked=$((blocked+1));return;fi;fi;if [ "$candidate_allowed" -gt 0 ];then allowed=$((allowed+1));else unresolved=$((unresolved+1));fi;}
classify_proftpd(){ f="${root}/etc/proftpd/proftpd.conf";[ -r "$f" ]||{ err=FTP_CONFIG_UNREADABLE;return;};if grep -Eiq '^[[:space:]]*Include[[:space:]]' "$f";then unresolved=$((unresolved+1));elif grep -Eiq '^[[:space:]]*RootLogin[[:space:]]+off' "$f";then blocked=$((blocked+1));elif grep -Eiq '^[[:space:]]*RootLogin[[:space:]]+on' "$f";then allowed=$((allowed+1));else unresolved=$((unresolved+1));fi;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for pair in vsftpd:vsftpd.service proftpd:proftpd.service ftp:ftp.service ftp:ftp.socket;do n=${pair%%:*};u=${pair#*:};if [ "$($s is-active "$u" 2>/dev/null||true)" = active ];then active=$((active+1));case "$n" in vsftpd)classify_vsftpd;;proftpd)classify_proftpd;;*)unresolved=$((unresolved+1));;esac;fi;done;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U57_FILE:-}" ];then fixture "$OS_GUARD_TEST_U57_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U57_COLLECTION_FAILED;basis='FTP runtime or root-login restriction could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"FTP root-login policy collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U57_FTP_INACTIVE;basis='No target FTP service is active'
elif [ "$allowed" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U57_ROOT_LOGIN_ALLOWED;basis='An active FTP daemon explicitly permits root FTP login'
elif [ "$blocked" -ge "$active" ]&&[ "$unresolved" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U57_ROOT_LOGIN_BLOCKED;basis='Every active FTP daemon explicitly blocks root FTP login'
else status_json=null;review_state=PENDING;reason=KISA_U57_POLICY_UNRESOLVED;basis='A nonstandard or included FTP login policy cannot be classified safely';fi
printf '{"item_id":"U-57","status":%s,"review_state":"%s","current_value":{"active_count":%s,"root_ftp_login_blocked":%s,"root_ftp_login_allowed":%s,"unresolved_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-57","collection_method":"Read-only active FTP daemon root-login policy inspection","active_count":%s,"root_ftp_login_blocked":%s,"root_ftp_login_allowed":%s,"unresolved_count":%s,"reason_code":' "$status_json" "$review_state" "$active" "$blocked" "$allowed" "$unresolved" "$complete" "$active" "$blocked" "$allowed" "$unresolved";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
