#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;active=0;inactive=0;unresolved=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked active inactive unresolved extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$checked" "$active" "$inactive" "$unresolved";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};for u in snmpd.service snmpd.socket snmptrapd.service snmptrapd.socket;do checked=$((checked+1));state=$($s is-active "$u" 2>/dev/null||true);case "$state" in active)active=$((active+1));;inactive|failed|unknown)inactive=$((inactive+1));;*)unresolved=$((unresolved+1));;esac;done;p=$(command -v pgrep 2>/dev/null||true);[ -n "$p" ]||{ err=PROCESS_QUERY_UNAVAILABLE;return;};for n in snmpd snmptrapd;do checked=$((checked+1));if $p -x "$n" >/dev/null 2>&1;then active=$((active+1));else inactive=$((inactive+1));fi;done;for f in "${root}/etc/inetd.conf" "${root}/etc/xinetd.d/snmpd" "${root}/etc/xinetd.d/snmptrapd";do [ -r "$f" ]||continue;grep -Eiq '^[[:space:]]*snmp(trap)?[[:space:]]|disable[[:space:]]*=[[:space:]]*no' "$f"&&active=$((active+1));done;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U58_FILE:-}" ];then fixture "$OS_GUARD_TEST_U58_FILE";else runtime;fi;fi
if [ "$active" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U58_SNMP_ACTIVE;basis='An SNMP service, socket, process, or legacy activation path is active'
elif [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U58_COLLECTION_FAILED;basis='SNMP activation state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"SNMP state collection failed"}')
elif [ "$unresolved" -gt 0 ];then status_json=null;review_state=PENDING;reason=KISA_U58_STATE_UNRESOLVED;basis='A nonstandard SNMP activation state cannot be classified safely'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U58_SNMP_INACTIVE;basis='All checked SNMP activation paths are inactive';fi
printf '{"item_id":"U-58","status":%s,"review_state":"%s","current_value":{"checked_count":%s,"active_count":%s,"inactive_count":%s,"unresolved_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-58","collection_method":"Read-only systemd, process, and legacy SNMP activation inspection","checked_count":%s,"active_count":%s,"inactive_count":%s,"unresolved_count":%s,"reason_code":' "$status_json" "$review_state" "$checked" "$active" "$inactive" "$unresolved" "$complete" "$checked" "$active" "$inactive" "$unresolved";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
