#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;v3=0;legacy=0;complex=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active v3 legacy complex extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$active" "$v3" "$legacy" "$complex";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);p=$(command -v pgrep 2>/dev/null||true);[ -n "$s" ]&&{ for u in snmpd.service snmpd.socket snmptrapd.service snmptrapd.socket;do [ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&active=$((active+1));done;};[ -n "$p" ]&&{ for n in snmpd snmptrapd;do $p -x "$n" >/dev/null 2>&1&&active=$((active+1));done;};[ -n "$s" ]||[ -n "$p" ]||{ err=SERVICE_QUERY_UNAVAILABLE;return;};[ "$active" -eq 0 ]&&{ complete=true;return;};f="${root}/etc/snmp/snmpd.conf";[ -r "$f" ]||{ err=SNMP_CONFIG_UNREADABLE;return;};legacy=$(grep -Eic '^[[:space:]]*(rocommunity6?|rwcommunity6?|com2sec6?)[[:space:]]+' "$f"||true);v3=$(grep -Eic '^[[:space:]]*(rouser|rwuser|authuser|createUser)[[:space:]]+' "$f"||true);complex=$(grep -Eic '^[[:space:]]*(include(File|Dir)?|dlmod)[[:space:]]+' "$f"||true);complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U59_FILE:-}" ];then fixture "$OS_GUARD_TEST_U59_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U59_COLLECTION_FAILED;basis='SNMP runtime or version policy could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"SNMP version-policy collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U59_SNMP_INACTIVE;basis='No SNMP service is active'
elif [ "$legacy" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U59_LEGACY_VERSION_ENABLED;basis='The active SNMP configuration enables a v1/v2c community security model'
elif [ "$v3" -gt 0 ]&&[ "$complex" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U59_V3_ONLY;basis='Only SNMPv3 user-based access is configured'
else status_json=null;review_state=PENDING;reason=KISA_U59_VERSION_UNRESOLVED;basis='Includes or nonstandard configuration prevent determination of the allowed SNMP versions';fi
printf '{"item_id":"U-59","status":%s,"review_state":"%s","current_value":{"snmp_active":%s,"v3_configured_count":%s,"legacy_version_enabled_count":%s,"complex_config_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-59","collection_method":"Read-only SNMP runtime and security-model directive inspection","snmp_active":%s,"v3_configured_count":%s,"legacy_version_enabled_count":%s,"complex_config_count":%s,"reason_code":' "$status_json" "$review_state" "$active" "$v3" "$legacy" "$complex" "$complete" "$active" "$v3" "$legacy" "$complex";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
