#!/bin/sh
set -u
set -f
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;checked=0;default_count=0;good=0;bad=0;v3=0;v3_evaluable=0;complex=0;min_length=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active checked default_count good bad v3 v3_evaluable complex min_length extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$active" "$checked" "$default_count" "$good" "$bad" "$v3" "$v3_evaluable" "$complex" "$min_length";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
assess(){ secret=$1;len=${#secret};checked=$((checked+1));[ "$min_length" -eq 0 ]||[ "$len" -ge "$min_length" ]||min_length=$len;[ "$min_length" -ne 0 ]||min_length=$len;case "$secret" in public|PUBLIC|Public|private|PRIVATE|Private)default_count=$((default_count+1));bad=$((bad+1));return;;esac;alpha=0;digit=0;special=0;case "$secret" in *[[:alpha:]]*)alpha=1;;esac;case "$secret" in *[[:digit:]]*)digit=1;;esac;case "$secret" in *[![:alnum:]]*)special=1;;esac;if [ "$alpha" -eq 1 ]&&[ "$digit" -eq 1 ]&&{ [ "$special" -eq 1 ]&&[ "$len" -ge 8 ]||[ "$len" -ge 10 ];};then good=$((good+1));else bad=$((bad+1));fi;secret='';}
scan_community(){ while IFS= read -r line||[ -n "$line" ];do case "$line" in ''|'#'*)continue;;esac;set -- $line;case "${1:-}" in rocommunity|rwcommunity|rocommunity6|rwcommunity6)[ "$#" -ge 2 ]&&assess "$2";;com2sec|com2sec6)[ "$#" -ge 4 ]&&assess "$4";;include|includeFile|includeDir)complex=$((complex+1));;rouser|rwuser|authuser)v3=$((v3+1));;esac;done < "$1";}
scan_v3(){ while IFS= read -r line||[ -n "$line" ];do set -- $line;[ "${1:-}" = createUser ]||continue;v3=$((v3+1));if [ "$#" -ge 4 ];then v3_evaluable=$((v3_evaluable+1));assess "$4";fi;done < "$1";}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);p=$(command -v pgrep 2>/dev/null||true);[ -n "$s" ]&&for u in snmpd.service snmpd.socket snmptrapd.service snmptrapd.socket;do [ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&active=$((active+1));done;[ -n "$p" ]&&for n in snmpd snmptrapd;do $p -x "$n" >/dev/null 2>&1&&active=$((active+1));done;[ -n "$s" ]||[ -n "$p" ]||{ err=SERVICE_QUERY_UNAVAILABLE;return;};[ "$active" -eq 0 ]&&{ complete=true;return;};f="${root}/etc/snmp/snmpd.conf";[ -r "$f" ]||{ err=SNMP_CONFIG_UNREADABLE;return;};scan_community "$f";vf="${root}/var/lib/net-snmp/snmpd.conf";[ -r "$vf" ]&&scan_v3 "$vf";complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U60_FILE:-}" ];then fixture "$OS_GUARD_TEST_U60_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U60_COLLECTION_FAILED;basis='SNMP credential complexity could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"SNMP credential-complexity collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U60_SNMP_INACTIVE;basis='No SNMP service is active'
elif [ "$bad" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U60_WEAK_CREDENTIAL;basis='At least one configured SNMP credential fails the KISA complexity rule'
elif [ "$checked" -gt 0 ]&&[ "$good" -eq "$checked" ]&&[ "$complex" -eq 0 ]&&{ [ "$v3" -eq 0 ]||[ "$v3" -eq "$v3_evaluable" ];};then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U60_COMPLEXITY_SATISFIED;basis='Every locally evaluable SNMP credential satisfies the KISA complexity rule'
else status_json=null;review_state=PENDING;reason=KISA_U60_SECRET_UNRESOLVED;basis='SNMPv3 protected credentials, includes, or dynamic configuration cannot be evaluated safely';fi
printf '{"item_id":"U-60","status":%s,"review_state":"%s","current_value":{"snmp_active":%s,"checked_secret_count":%s,"default_value_detected_count":%s,"complexity_satisfied_count":%s,"complexity_failed_count":%s,"v3_configured_count":%s,"v3_evaluable_count":%s,"minimum_length":%s,"collection_complete":%s},"evidence":{"item_id":"U-60","collection_method":"In-memory SNMP credential complexity analysis without secret retention","snmp_active":%s,"checked_secret_count":%s,"default_value_detected_count":%s,"complexity_satisfied_count":%s,"complexity_failed_count":%s,"v3_evaluable_count":%s,"minimum_length":%s,"reason_code":' "$status_json" "$review_state" "$active" "$checked" "$default_count" "$good" "$bad" "$v3" "$v3_evaluable" "$min_length" "$complete" "$active" "$checked" "$default_count" "$good" "$bad" "$v3_evaluable" "$min_length";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
