#!/bin/sh
set -u
set -f
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;control=0;unrestricted=0;restricted=0;complex=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active control unrestricted restricted complex extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$active" "$control" "$unrestricted" "$restricted" "$complex";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);p=$(command -v pgrep 2>/dev/null||true);[ -n "$s" ]&&for u in snmpd.service snmpd.socket snmptrapd.service snmptrapd.socket;do [ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&active=$((active+1));done;[ -n "$p" ]&&for n in snmpd snmptrapd;do $p -x "$n" >/dev/null 2>&1&&active=$((active+1));done;[ -n "$s" ]||[ -n "$p" ]||{ err=SERVICE_QUERY_UNAVAILABLE;return;};[ "$active" -eq 0 ]&&{ complete=true;return;};f="${root}/etc/snmp/snmpd.conf";[ -r "$f" ]||{ err=SNMP_CONFIG_UNREADABLE;return;};while IFS= read -r line||[ -n "$line" ];do set -- $line;case "${1:-}" in rocommunity|rwcommunity|rocommunity6|rwcommunity6)control=$((control+1));source=${3:-default};case "$source" in default|0.0.0.0|0.0.0.0/0|::/0|any|ANY)unrestricted=$((unrestricted+1));;*)restricted=$((restricted+1));;esac;;com2sec|com2sec6)control=$((control+1));source=${3:-default};case "$source" in default|0.0.0.0|0.0.0.0/0|::/0|any|ANY)unrestricted=$((unrestricted+1));;*)restricted=$((restricted+1));;esac;;rouser|rwuser)control=$((control+1));restricted=$((restricted+1));;include|includeFile|includeDir|access|group|view)complex=$((complex+1));;esac;done < "$f";complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U61_FILE:-}" ];then fixture "$OS_GUARD_TEST_U61_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U61_COLLECTION_FAILED;basis='SNMP service or access-control policy could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"SNMP access-control collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U61_SNMP_INACTIVE;basis='No SNMP service is active'
elif [ "$unrestricted" -gt 0 ]||{ [ "$control" -eq 0 ]&&[ "$complex" -eq 0 ];};then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U61_ACCESS_UNRESTRICTED;basis='SNMP access control is absent or permits an unrestricted source'
elif [ "$restricted" -gt 0 ]&&[ "$restricted" -eq "$control" ]&&[ "$complex" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U61_ACCESS_RESTRICTED;basis='Every directly configured SNMP access rule is restricted'
else status_json=null;review_state=PENDING;reason=KISA_U61_ACCESS_SCOPE_UNRESOLVED;basis='Includes, external ACLs, or complex VACM prevent a safe effective-scope conclusion';fi
printf '{"item_id":"U-61","status":%s,"review_state":"%s","current_value":{"snmp_active":%s,"access_control_present":%s,"unrestricted_access_count":%s,"restricted_source_count":%s,"complex_policy_count":%s,"collection_complete":%s},"evidence":{"item_id":"U-61","collection_method":"Read-only aggregate SNMP source and VACM access-policy inspection","snmp_active":%s,"access_control_present":%s,"unrestricted_access_count":%s,"restricted_source_count":%s,"complex_policy_count":%s,"reason_code":' "$status_json" "$review_state" "$active" "$control" "$unrestricted" "$restricted" "$complex" "$complete" "$active" "$control" "$unrestricted" "$restricted" "$complex";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
