#!/bin/sh
set -u
set -f
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;system_warning=0;telnet_active=0;telnet_warning=0;ftp_active=0;ftp_warning=0;smtp_active=0;smtp_warning=0;dns_active=0;dns_warning=0;required=1;configured=0;missing=0;complex=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
warning_text(){ printf '%s' "$1"|grep -Eiq '(authori[sz]ed|unauthori[sz]ed|prohibit|restricted|monitor|consent|warning|legal action|무단|허가|인가|경고)'; }
warning_file(){ [ -r "$1" ]&&[ -s "$1" ]&&grep -Eiq '(authori[sz]ed|unauthori[sz]ed|prohibit|restricted|monitor|consent|warning|legal action|무단|허가|인가|경고)' "$1"; }
fixture(){ IFS='|' read -r state system_warning telnet_active telnet_warning ftp_active ftp_warning smtp_active smtp_warning dns_active dns_warning complex extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$system_warning" "$telnet_active" "$telnet_warning" "$ftp_active" "$ftp_warning" "$smtp_active" "$smtp_warning" "$dns_active" "$dns_warning" "$complex";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;required=$((1+telnet_active+ftp_active+smtp_active+dns_active));configured=$((system_warning+telnet_warning+ftp_warning+smtp_warning+dns_warning));[ "$system_warning" -gt 0 ]||missing=$((missing+1));if [ "$complex" -eq 0 ];then [ "$telnet_active" -eq 0 ]||[ "$telnet_warning" -gt 0 ]||missing=$((missing+1));[ "$ftp_active" -eq 0 ]||[ "$ftp_warning" -gt 0 ]||missing=$((missing+1));[ "$smtp_active" -eq 0 ]||[ "$smtp_warning" -gt 0 ]||missing=$((missing+1));[ "$dns_active" -eq 0 ]||[ "$dns_warning" -gt 0 ]||missing=$((missing+1));fi;}
system_check(){ warning_file "${root}/etc/issue"&&system_warning=1;warning_file "${root}/etc/issue.net"&&system_warning=1;f="${root}/etc/ssh/sshd_config";if [ -r "$f" ];then banner=$(grep -Ei '^[[:space:]]*Banner[[:space:]]+[^nN][^oO][^nN][^eE]' "$f"|tail -n1|awk '{print $2}');if [ -n "$banner" ]&&warning_file "${root}${banner}";then system_warning=1;fi;fi;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};system_check;for u in telnet.service telnet.socket;do [ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&telnet_active=1;done;if [ "$telnet_active" -gt 0 ];then required=$((required+1));warning_file "${root}/etc/issue.net"&&telnet_warning=1;[ "$telnet_warning" -gt 0 ]||missing=$((missing+1));fi
ftp_kind='';for pair in vsftpd:vsftpd.service proftpd:proftpd.service;do n=${pair%%:*};u=${pair#*:};[ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&{ ftp_active=1;ftp_kind=$n;};done;if [ "$ftp_active" -gt 0 ];then required=$((required+1));case "$ftp_kind" in vsftpd)f="${root}/etc/vsftpd/vsftpd.conf";[ -r "$f" ]||f="${root}/etc/vsftpd.conf";[ -r "$f" ]||{ err=FTP_CONFIG_UNREADABLE;return;};v=$(grep -Ei '^[[:space:]]*ftpd_banner[[:space:]]*=' "$f"|tail -n1|cut -d= -f2-);warning_text "$v"&&ftp_warning=1;;proftpd)f="${root}/etc/proftpd/proftpd.conf";[ -r "$f" ]||{ err=FTP_CONFIG_UNREADABLE;return;};grep -Eiq '^[[:space:]]*Include[[:space:]]' "$f"&&complex=$((complex+1));p=$(grep -Ei '^[[:space:]]*DisplayLogin[[:space:]]+' "$f"|tail -n1|awk '{print $2}');if [ -n "$p" ]&&warning_file "${root}${p}";then ftp_warning=1;fi;;esac;[ "$ftp_warning" -gt 0 ]||[ "$complex" -gt 0 ]||missing=$((missing+1));fi
smtp_kind='';for pair in postfix:postfix.service sendmail:sendmail.service exim:exim4.service;do n=${pair%%:*};u=${pair#*:};[ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&{ smtp_active=1;smtp_kind=$n;};done;if [ "$smtp_active" -gt 0 ];then required=$((required+1));case "$smtp_kind" in postfix)f="${root}/etc/postfix/main.cf";[ -r "$f" ]||{ err=SMTP_CONFIG_UNREADABLE;return;};v=$(grep -Ei '^[[:space:]]*smtpd_banner[[:space:]]*=' "$f"|tail -n1|cut -d= -f2-);warning_text "$v"&&smtp_warning=1;;sendmail)f="${root}/etc/mail/sendmail.cf";[ -r "$f" ]||{ err=SMTP_CONFIG_UNREADABLE;return;};v=$(grep -Ei '^[[:space:]]*O[[:space:]]*SmtpGreetingMessage[[:space:]]*=' "$f"|tail -n1|cut -d= -f2-);warning_text "$v"&&smtp_warning=1;;exim)f="${root}/etc/exim4/exim4.conf.template";[ -r "$f" ]||{ err=SMTP_CONFIG_UNREADABLE;return;};grep -Eiq '^[[:space:]]*\.include' "$f"&&complex=$((complex+1));v=$(grep -Ei '^[[:space:]]*smtp_banner[[:space:]]*=' "$f"|tail -n1|cut -d= -f2-);warning_text "$v"&&smtp_warning=1;;esac;[ "$smtp_warning" -gt 0 ]||[ "$complex" -gt 0 ]||missing=$((missing+1));fi
for u in named.service bind9.service;do [ "$($s is-active "$u" 2>/dev/null||true)" = active ]&&dns_active=1;done;if [ "$dns_active" -gt 0 ];then required=$((required+1));f="${root}/etc/named.conf";[ -r "$f" ]||f="${root}/etc/bind/named.conf.options";[ -r "$f" ]||{ err=DNS_CONFIG_UNREADABLE;return;};grep -Eiq '^[[:space:]]*include[[:space:]]' "$f"&&complex=$((complex+1));grep -Eiq 'version[[:space:]]+(none|"(unknown|not currently available|restricted)")[[:space:]]*;' "$f"&&dns_warning=1;[ "$dns_warning" -gt 0 ]||[ "$complex" -gt 0 ]||missing=$((missing+1));fi
configured=$((system_warning+telnet_warning+ftp_warning+smtp_warning+dns_warning));[ "$system_warning" -gt 0 ]||missing=$((missing+1));complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U62_FILE:-}" ];then fixture "$OS_GUARD_TEST_U62_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U62_COLLECTION_FAILED;basis='Required login-warning state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"Login-warning collection failed"}')
elif [ "$missing" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U62_WARNING_MISSING;basis='A required server or active-service login warning is missing'
elif [ "$complex" -gt 0 ];then status_json=null;review_state=PENDING;reason=KISA_U62_WARNING_UNRESOLVED;basis='A dynamic, included, or nonstandard banner cannot be classified safely'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U62_WARNINGS_CONFIGURED;basis='The server and every active target service have an applicable warning or disclosure restriction';fi
printf '{"item_id":"U-62","status":%s,"review_state":"%s","current_value":{"system_warning_configured":%s,"telnet_active":%s,"telnet_warning_configured":%s,"ftp_active":%s,"ftp_warning_configured":%s,"smtp_active":%s,"smtp_warning_configured":%s,"dns_active":%s,"dns_warning_configured":%s,"required_warning_count":%s,"configured_warning_count":%s,"missing_warning_count":%s,"complex_banner_count":%s},"evidence":{"item_id":"U-62","collection_method":"Read-only aggregate login-warning applicability inspection without banner content retention","system_warning_configured":%s,"telnet_active":%s,"telnet_warning_configured":%s,"ftp_active":%s,"ftp_warning_configured":%s,"smtp_active":%s,"smtp_warning_configured":%s,"dns_active":%s,"dns_warning_configured":%s,"missing_warning_count":%s,"reason_code":' "$status_json" "$review_state" "$system_warning" "$telnet_active" "$telnet_warning" "$ftp_active" "$ftp_warning" "$smtp_active" "$smtp_warning" "$dns_active" "$dns_warning" "$required" "$configured" "$missing" "$complex" "$system_warning" "$telnet_active" "$telnet_warning" "$ftp_active" "$ftp_warning" "$smtp_active" "$smtp_warning" "$dns_active" "$dns_warning" "$missing";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
