#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;checked=0;owner_ok=0;mode=unknown;extra_permission=0;more_restrictive=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state checked owner_ok mode extra_permission more_restrictive extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$checked" "$owner_ok" "$extra_permission" "$more_restrictive";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;case "$mode" in [0-7][0-7][0-7]|[0-7][0-7][0-7][0-7]);;*)err=METADATA_PARSE_FAILED;;esac;}
runtime(){ f="${root}/etc/sudoers";[ -e "$f" ]||{ err=SUDOERS_MISSING;return;};data=$(stat -c '%u|%U|%a' "$f" 2>/dev/null)||{ err=STAT_FAILED;return;};IFS='|' read -r uid owner mode extra <<EOF
$data
EOF
[ -z "${extra:-}" ]&&case "$uid:$owner:$mode" in 0:root:[0-7][0-7][0-7]|0:root:[0-7][0-7][0-7][0-7])owner_ok=1;;*:*:[0-7][0-7][0-7]|*:*:[0-7][0-7][0-7][0-7])owner_ok=0;;*)err=METADATA_PARSE_FAILED;return;;esac;checked=1;m=$mode;[ ${#m} -eq 3 ]||{ special=${m%???};[ "$special" = 0 ]||extra_permission=1;m=${m#?};};u=${m%??};rest=${m#?};g=${rest%?};o=${rest#?};case "$u" in 1|3|5|7)extra_permission=1;;esac;case "$g" in 1|2|3|5|6|7)extra_permission=1;;esac;[ "$o" = 0 ]||extra_permission=1;if [ "$extra_permission" -eq 0 ]&&[ "$m" != 640 ];then more_restrictive=1;fi;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U63_FILE:-}" ];then fixture "$OS_GUARD_TEST_U63_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U63_COLLECTION_FAILED;basis='sudoers ownership or mode metadata could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"sudoers metadata collection failed"}')
elif [ "$owner_ok" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U63_OWNER_NOT_ROOT;basis='The sudoers file owner is not consistently root'
elif [ "$extra_permission" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U63_PERMISSION_EXCEEDS_0640;basis='The sudoers file grants permission bits not allowed by mode 0640'
elif [ "$mode" = 640 ]||[ "$mode" = 0640 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U63_ROOT_0640;basis='The sudoers file is owned by root with exact mode 0640'
else status_json=null;review_state=PENDING;reason=KISA_U63_MORE_RESTRICTIVE_MODE;basis='The file mode is more restrictive than 0640, while the KISA good criterion states exact mode 0640';fi
printf '{"item_id":"U-63","status":%s,"review_state":"%s","current_value":{"metadata_checked":%s,"owner_is_root":%s,"permission_mode":' "$status_json" "$review_state" "$checked" "$owner_ok";os_guard_json_quote "$mode";printf ',"extra_permission_present":%s,"more_restrictive_than_0640":%s},"evidence":{"item_id":"U-63","collection_method":"Read-only stat metadata inspection of /etc/sudoers","metadata_checked":%s,"owner_is_root":%s,"permission_mode":' "$extra_permission" "$more_restrictive" "$checked" "$owner_ok";os_guard_json_quote "$mode";printf ',"extra_permission_present":%s,"reason_code":' "$extra_permission";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
