#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;known=0;pending=0;policy=0;periodic=0;manager=unknown;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state known pending policy periodic manager extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$known" "$pending" "$policy" "$periodic";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;case "$manager" in dnf|apt|unknown);;*)err=RESULT_PARSE_FAILED;;esac;}
rocky_check(){ manager=dnf;d=$(command -v dnf 2>/dev/null||true);[ -n "$d" ]||{ err=PACKAGE_MANAGER_UNAVAILABLE;return;};out=$($d -q --cacheonly check-update --security 2>/dev/null);rc=$?;case "$rc" in 0)known=1;pending=0;;100)known=1;pending=$(printf '%s\n' "$out"|grep -Ec '^[[:alnum:]_.+-]+[[:space:]]+[^[:space:]]+[[:space:]]+[^[:space:]]+'||true);[ "$pending" -gt 0 ]||known=0;;*)err=PACKAGE_METADATA_UNAVAILABLE;return;;esac;[ -s "${root}/var/log/dnf.log" ]&&periodic=$((periodic+1));}
ubuntu_check(){ manager=apt;a=$(command -v apt-get 2>/dev/null||true);[ -n "$a" ]||{ err=PACKAGE_MANAGER_UNAVAILABLE;return;};out=$($a -s upgrade 2>/dev/null);rc=$?;[ "$rc" -eq 0 ]||{ err=PACKAGE_METADATA_UNAVAILABLE;return;};known=1;pending=$(printf '%s\n' "$out"|grep -Eic '^Inst[[:space:]].*(-security|security\.ubuntu\.com)'||true);[ -s "${root}/var/log/apt/history.log" ]&&periodic=$((periodic+1));}
runtime(){ case "$distro" in rocky)rocky_check;;ubuntu)ubuntu_check;;*)err=UNSUPPORTED_OS_CONFIGURATION;return;;esac;[ -z "$err" ]&&complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U64_FILE:-}" ];then fixture "$OS_GUARD_TEST_U64_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ]||[ "$known" -eq 0 ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U64_COLLECTION_FAILED;basis='Offline package security-update state could not be determined';code=${err:-UPDATE_STATE_UNKNOWN};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"Patch-state collection failed"}')
elif [ "$pending" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U64_SECURITY_UPDATES_PENDING;basis='Locally cached vendor metadata identifies unapplied security updates'
elif [ "$policy" -gt 0 ]&&[ "$periodic" -gt 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U64_POLICY_AND_MAINTENANCE_VERIFIED;basis='Patch policy, periodic management, and current local security-update state are verified'
else status_json=null;review_state=PENDING;reason=KISA_U64_POLICY_REVIEW_REQUIRED;basis='No cached security update is identified, but organizational policy and periodic application cannot be verified locally';fi
printf '{"item_id":"U-64","status":%s,"review_state":"%s","current_value":{"package_manager":' "$status_json" "$review_state";os_guard_json_quote "$manager";printf ',"security_updates_pending_count":%s,"update_state_known":%s,"policy_verified":%s,"periodic_management_evidence_count":%s},"evidence":{"item_id":"U-64","collection_method":"Read-only offline package metadata and aggregate package-management evidence inspection","package_manager":' "$pending" "$known" "$policy" "$periodic";os_guard_json_quote "$manager";printf ',"security_updates_pending_count":%s,"update_state_known":%s,"policy_verified":%s,"periodic_management_evidence_count":%s,"reason_code":' "$pending" "$known" "$policy" "$periodic";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel_version":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
