#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;server=0;synchronized=0;sync_known=0;approved=0;sources=0;service=none;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active server synchronized sync_known approved sources service extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$active" "$server" "$synchronized" "$sync_known" "$approved" "$sources";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;case "$service" in chrony|ntp|timesyncd|none|nonstandard);;*)err=RESULT_PARSE_FAILED;;esac;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};if [ "$($s is-active chronyd.service 2>/dev/null||true)" = active ]||[ "$($s is-active chrony.service 2>/dev/null||true)" = active ];then active=1;service=chrony;f="${root}/etc/chrony.conf";[ -r "$f" ]||f="${root}/etc/chrony/chrony.conf";[ -r "$f" ]||{ err=TIME_CONFIG_UNREADABLE;return;};sources=$(grep -Eic '^[[:space:]]*(server|pool)[[:space:]]+[^[:space:]#]+' "$f"||true);[ "$sources" -gt 0 ]&&server=1;c=$(command -v chronyc 2>/dev/null||true);if [ -n "$c" ];then out=$($c tracking 2>/dev/null||true);if printf '%s' "$out"|grep -Eiq 'Leap status[[:space:]]*:[[:space:]]*Normal';then synchronized=1;sync_known=1;elif printf '%s' "$out"|grep -Eiq 'Leap status[[:space:]]*:[[:space:]]*Not synchronised';then sync_known=1;fi;fi
elif [ "$($s is-active ntpd.service 2>/dev/null||true)" = active ]||[ "$($s is-active ntp.service 2>/dev/null||true)" = active ];then active=1;service=ntp;f="${root}/etc/ntp.conf";[ -r "$f" ]||{ err=TIME_CONFIG_UNREADABLE;return;};sources=$(grep -Eic '^[[:space:]]*(server|pool)[[:space:]]+[^[:space:]#]+' "$f"||true);[ "$sources" -gt 0 ]&&server=1;n=$(command -v ntpq 2>/dev/null||true);if [ -n "$n" ];then out=$($n -pn 2>/dev/null||true);sync_known=1;printf '%s\n' "$out"|grep -Eq '^\*'&&synchronized=1;fi
elif [ "$($s is-active systemd-timesyncd.service 2>/dev/null||true)" = active ];then active=1;service=timesyncd;for f in "${root}/etc/systemd/timesyncd.conf" "${root}/etc/systemd/timesyncd.conf.d"/*.conf;do [ -r "$f" ]||continue;c=$(grep -Eic '^[[:space:]]*(NTP|FallbackNTP)[[:space:]]*=[[:space:]]*[^[:space:]#]+' "$f"||true);sources=$((sources+c));done;t=$(command -v timedatectl 2>/dev/null||true);if [ -n "$t" ];then runtime_source=$($t show-timesync --property=ServerName --value 2>/dev/null||true);[ -z "$runtime_source" ]||sources=$((sources+1));runtime_source='';value=$($t show -p NTPSynchronized --value 2>/dev/null||true);case "$value" in yes)sync_known=1;synchronized=1;;no)sync_known=1;;esac;fi;[ "$sources" -gt 0 ]&&server=1;fi;complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U65_FILE:-}" ];then fixture "$OS_GUARD_TEST_U65_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U65_COLLECTION_FAILED;basis='Time synchronization service, configuration, or state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"Time-synchronization collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U65_SERVICE_INACTIVE;basis='No supported time synchronization service is active'
elif [ "$server" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U65_SERVER_NOT_CONFIGURED;basis='The active time synchronization service has no configured source'
elif [ "$sync_known" -gt 0 ]&&[ "$synchronized" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U65_NOT_SYNCHRONIZED;basis='The active time service reports that the system is not synchronized'
elif [ "$sync_known" -eq 0 ];then status_json=null;review_state=PENDING;reason=KISA_U65_SYNC_STATE_UNRESOLVED;basis='Runtime synchronization state is unavailable or temporarily indeterminate'
elif [ "$approved" -eq 0 ];then status_json=null;review_state=PENDING;reason=KISA_U65_SOURCE_APPROVAL_REQUIRED;basis='Synchronization is active, but organizational approval of the configured source requires review'
else status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U65_SYNCHRONIZED;basis='An approved configured time service is active and reports synchronization';fi
printf '{"item_id":"U-65","status":%s,"review_state":"%s","current_value":{"time_sync_service":' "$status_json" "$review_state";os_guard_json_quote "$service";printf ',"service_active":%s,"server_configured":%s,"synchronized":%s,"sync_state_known":%s,"source_approval_verified":%s,"source_count":%s},"evidence":{"item_id":"U-65","collection_method":"Read-only time service, aggregate source configuration, and synchronization-state inspection","time_sync_service":' "$active" "$server" "$synchronized" "$sync_known" "$approved" "$sources";os_guard_json_quote "$service";printf ',"service_active":%s,"server_configured":%s,"synchronized":%s,"sync_state_known":%s,"source_approval_verified":%s,"source_count":%s,"reason_code":' "$active" "$server" "$synchronized" "$sync_known" "$approved" "$sources";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
