#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;active=0;output=0;policy=0;rules=0;complex=0;backend=none;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state active output policy rules complex backend extra < "$1"||true;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$active" "$output" "$policy" "$rules" "$complex";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;case "$backend" in rsyslog|journald|syslog|mixed|none);;*)err=RESULT_PARSE_FAILED;;esac;}
runtime(){ s=$(command -v systemctl 2>/dev/null||true);[ -n "$s" ]||{ err=SYSTEMCTL_UNAVAILABLE;return;};rs=0;jr=0;sy=0;[ "$($s is-active rsyslog.service 2>/dev/null||true)" = active ]&&rs=1;[ "$($s is-active systemd-journald.service 2>/dev/null||true)" = active ]&&jr=1;[ "$($s is-active syslog.service 2>/dev/null||true)" = active ]&&sy=1;active=$((rs+jr+sy));if [ "$active" -gt 1 ];then backend=mixed;elif [ "$rs" -gt 0 ];then backend=rsyslog;elif [ "$jr" -gt 0 ];then backend=journald;elif [ "$sy" -gt 0 ];then backend=syslog;fi;[ "$active" -eq 0 ]&&{ complete=true;return;};if [ "$rs" -gt 0 ];then f="${root}/etc/rsyslog.conf";[ -r "$f" ]||{ err=RSYSLOG_CONFIG_UNREADABLE;return;};rules=$(grep -Eic '^[[:space:]]*[^#$[:space:]][^[:space:]]*\.[^[:space:]]+[[:space:]]+[^[:space:]]+' "$f"||true);inc=$(grep -Eic '^[[:space:]]*(\$IncludeConfig|include\()[[:space:]]*' "$f"||true);[ "$inc" -gt 0 ]&&complex=$((complex+inc));for d in "${root}/etc/rsyslog.d"/*.conf;do [ -r "$d" ]||continue;c=$(grep -Eic '^[[:space:]]*[^#$[:space:]][^[:space:]]*\.[^[:space:]]+[[:space:]]+[^[:space:]]+' "$d"||true);rules=$((rules+c));grep -Eiq '(^|[[:space:]])@@?[^[:space:]]+' "$d"&&complex=$((complex+1));done;fi;if [ "$jr" -gt 0 ];then f="${root}/etc/systemd/journald.conf";[ -r "$f" ]||{ err=JOURNALD_CONFIG_UNREADABLE;return;};grep -Eiq '^[[:space:]]*Storage[[:space:]]*=[[:space:]]*none' "$f"&&rules=0||rules=$((rules+1));fi;logroot="${root}/var/log";[ -d "$logroot" ]||{ err=LOG_DIRECTORY_UNAVAILABLE;return;};found=$(find "$logroot" -xdev -type f -size +0c -print -quit 2>/dev/null);rc=$?;[ "$rc" -eq 0 ]||{ err=LOG_OUTPUT_SCAN_FAILED;return;};if [ -z "$found" ]&&[ "$jr" -gt 0 ];then for logroot in "${root}/run/log/journal" "${root}/var/log/journal";do [ -d "$logroot" ]||continue;found=$(find "$logroot" -xdev -type f -size +0c -print -quit 2>/dev/null);rc=$?;[ "$rc" -eq 0 ]||{ err=LOG_OUTPUT_SCAN_FAILED;return;};[ -z "$found" ]||break;done;fi;[ -n "$found" ]&&output=1;found='';complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U66_FILE:-}" ];then fixture "$OS_GUARD_TEST_U66_FILE";else runtime;fi;fi
if [ -n "$err" ]||[ "$complete" != true ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U66_COLLECTION_FAILED;basis='Logging service, configuration, or output state could not be collected';code=${err:-INCOMPLETE};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"Logging-policy collection failed"}')
elif [ "$active" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U66_LOGGING_INACTIVE;basis='No supported system logging backend is active'
elif [ "$output" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U66_LOG_OUTPUT_ABSENT;basis='The active logging backend has no observable non-empty local log output'
elif [ "$rules" -eq 0 ]&&[ "$complex" -eq 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U66_REQUIRED_RULES_ABSENT;basis='No local logging rule or enabled journald storage policy is present'
elif [ "$policy" -gt 0 ]&&[ "$complex" -eq 0 ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U66_POLICY_VERIFIED;basis='Logging is active, output is present, and the registered security logging policy is verified'
else status_json=null;review_state=PENDING;reason=KISA_U66_POLICY_REVIEW_REQUIRED;basis='Logging is operational, but organizational policy alignment or complex forwarding requires review';fi
printf '{"item_id":"U-66","status":%s,"review_state":"%s","current_value":{"logging_active":%s,"logging_backend":' "$status_json" "$review_state" "$active";os_guard_json_quote "$backend";printf ',"log_output_present":%s,"policy_verified":%s,"required_rules_present_count":%s,"complex_config_count":%s},"evidence":{"item_id":"U-66","collection_method":"Read-only logging service, aggregate rule, and file-metadata inspection without log content","logging_active":%s,"logging_backend":' "$output" "$policy" "$rules" "$complex" "$active";os_guard_json_quote "$backend";printf ',"log_output_present":%s,"policy_verified":%s,"required_rules_present_count":%s,"complex_config_count":%s,"reason_code":' "$output" "$policy" "$rules" "$complex";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
