#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd);. "$SCRIPT_DIR/../lib/common.sh"
distro=${OS_GUARD_DISTRO:-unknown};version_id=${OS_GUARD_VERSION_ID:-unknown};module_version=${OS_GUARD_MODULE_VERSION:-unknown};observed_at=$(os_guard_utc_now);kernel=$(uname -r 2>/dev/null||printf unknown);root=${OS_GUARD_TEST_ROOT:-}
status_json=null;review_state=PENDING;error_json=null;scanned=0;root_owned=0;safe=0;violations=0;unresolved=0;scan_failed=0;complete=false;err=''
case "$distro:$version_id" in rocky:9|rocky:9.*|rocky:10|rocky:10.*|ubuntu:22|ubuntu:22.*|ubuntu:24|ubuntu:24.*);;*)err=UNSUPPORTED_OS_CONFIGURATION;;esac
fixture(){ IFS='|' read -r state a b c d e f extra < "$1"||true;if [ "$state" = metadata ];then uid=$a;owner=$b;mode=$c;scan_failed=$d;scanned=1;case "$uid" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;case "$scan_failed" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;if [ "$uid" = 0 ]&&[ "$owner" = root ];then root_owned=1;elif [ "$uid" = 0 ];then unresolved=1;else violations=1;fi;if safe_mode "$mode";then safe=1;else violations=1;fi;complete=true;else scanned=$a;root_owned=$b;safe=$c;violations=$d;unresolved=$e;scan_failed=$f;[ "$state" = complete ]&&complete=true||err=COLLECTION_FAILED;for v in "$scanned" "$root_owned" "$safe" "$violations" "$unresolved" "$scan_failed";do case "$v" in ''|*[!0-9]*)err=RESULT_PARSE_FAILED;;esac;done;fi;}
safe_mode(){ m=$1;[ ${#m} -eq 3 ]||{ special=${m%???};[ "$special" = 0 ]||return 1;m=${m#?};};u=${m%??};rest=${m#?};g=${rest%?};o=${rest#?};case "$u" in 0|2|4|6);;*)return 1;;esac;case "$g" in 0|4);;*)return 1;;esac;case "$o" in 0|4);;*)return 1;;esac;return 0;}
runtime(){ dir="${root}/var/log";[ -d "$dir" ]||{ err=LOG_DIRECTORY_UNAVAILABLE;return;};metadata=$(find "$dir" -xdev -type f -printf '%U|%u|%m\n' 2>/dev/null);rc=$?;[ "$rc" -eq 0 ]||scan_failed=1;while IFS='|' read -r uid owner mode extra;do [ -n "$uid" ]||continue;case "$uid:$owner:$mode:${extra:-}" in [0-9]*:*:[0-7][0-7][0-7]:|[0-9]*:*:[0-7][0-7][0-7][0-7]:);;*)unresolved=$((unresolved+1));continue;;esac;scanned=$((scanned+1));file_bad=0;if [ "$uid" = 0 ]&&[ "$owner" = root ];then root_owned=$((root_owned+1));elif [ "$uid" = 0 ];then unresolved=$((unresolved+1));else file_bad=1;fi;if safe_mode "$mode";then safe=$((safe+1));else file_bad=1;fi;[ "$file_bad" -eq 0 ]||violations=$((violations+1));done <<EOF
$metadata
EOF
[ "$scanned" -gt 0 ]||{ err=NO_LOG_FILES;return;};complete=true;}
if [ -z "$err" ];then if [ -n "${OS_GUARD_TEST_U67_FILE:-}" ];then fixture "$OS_GUARD_TEST_U67_FILE";else runtime;fi;fi
if [ "$violations" -gt 0 ];then status_json='"VULNERABLE"';review_state=NOT_REQUIRED;reason=KISA_U67_FILE_VIOLATION;basis='At least one regular log file has a non-root owner or permission bits outside the 0644 subset'
elif [ -n "$err" ]||[ "$complete" != true ]||[ "$scan_failed" -gt 0 ];then status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U67_SCAN_INCOMPLETE;basis='The log-file metadata scan could not be completed';code=${err:-PARTIAL_SCAN};error_json=$(printf '{"code":';os_guard_json_quote "$code";printf ',"message":"Log metadata scan failed or was incomplete"}')
elif [ "$unresolved" -gt 0 ];then status_json=null;review_state=PENDING;reason=KISA_U67_OWNER_IDENTITY_UNRESOLVED;basis='Owner identity metadata is inconsistent or cannot be resolved safely'
elif [ "$root_owned" -eq "$scanned" ]&&[ "$safe" -eq "$scanned" ];then status_json='"GOOD"';review_state=NOT_REQUIRED;reason=KISA_U67_ALL_FILES_SAFE;basis='Every scanned regular log file is root-owned and uses a permission subset of 0644'
else status_json='"UNCHECKABLE"';review_state=NOT_REQUIRED;reason=KISA_U67_AGGREGATE_INCONSISTENT;basis='Log metadata aggregates are incomplete';error_json='{"code":"AGGREGATE_INCONSISTENT","message":"Log metadata aggregates are inconsistent"}';fi
printf '{"item_id":"U-67","status":%s,"review_state":"%s","current_value":{"scanned_file_count":%s,"root_owned_count":%s,"safe_mode_count":%s,"violation_count":%s,"unresolved_count":%s,"scan_failure_count":%s},"evidence":{"item_id":"U-67","collection_method":"Read-only aggregate metadata scan of regular files below /var/log","scanned_file_count":%s,"root_owned_count":%s,"safe_mode_count":%s,"violation_count":%s,"unresolved_count":%s,"scan_failure_count":%s,"reason_code":' "$status_json" "$review_state" "$scanned" "$root_owned" "$safe" "$violations" "$unresolved" "$scan_failed" "$scanned" "$root_owned" "$safe" "$violations" "$unresolved" "$scan_failed";os_guard_json_quote "$reason";printf ',"os":{"distro":';os_guard_json_quote "$distro";printf ',"version_id":';os_guard_json_quote "$version_id";printf '},"kernel":';os_guard_json_quote "$kernel";printf ',"module_version":';os_guard_json_quote "$module_version";printf ',"observed_at":';os_guard_json_quote "$observed_at";printf ',"judgment_basis":';os_guard_json_quote "$basis";printf '},"error":%s}\n' "$error_json"
